use cas_ast::{Context, Expr, ExprId};
use num_traits::{Signed, ToPrimitive};

/// Estimate number of terms generated by expansion.
/// Returns `None` if the expression is not expandable or cannot be estimated.
pub fn estimate_expand_terms(ctx: &Context, expr: ExprId) -> Option<u64> {
    estimate_expanded_term_count(ctx, expr)
}

/// Recursively estimate term count after expansion.
/// For `Pow(Add, n)`: multinomial count C(n+k-1, k-1).
/// For `Mul(a, b)`: product of expanded term counts.
/// For `Add/Sub`: sum of expanded term counts.
fn estimate_expanded_term_count(ctx: &Context, expr: ExprId) -> Option<u64> {
    match ctx.get(expr) {
        Expr::Pow(base, exp) => {
            let n = match ctx.get(*exp) {
                Expr::Number(num) => {
                    if !num.is_integer() || num.is_negative() {
                        return None;
                    }
                    num.to_integer().to_u32()?
                }
                _ => return None,
            };

            let k = count_add_terms(ctx, *base);
            if k < 2 || n < 2 {
                return Some(1);
            }

            crate::multinomial_expand::multinomial_term_count(n, k, u64::MAX as usize)
                .map(|count| count as u64)
        }
        Expr::Mul(l, r) => {
            let l_terms = estimate_expanded_term_count(ctx, *l).unwrap_or(1);
            let r_terms = estimate_expanded_term_count(ctx, *r).unwrap_or(1);
            l_terms.checked_mul(r_terms)
        }
        Expr::Add(l, r) | Expr::Sub(l, r) => {
            let l_terms = estimate_expanded_term_count(ctx, *l).unwrap_or(1);
            let r_terms = estimate_expanded_term_count(ctx, *r).unwrap_or(1);
            l_terms.checked_add(r_terms)
        }
        Expr::Neg(e) => estimate_expanded_term_count(ctx, *e),
        _ => Some(1),
    }
}

/// Count number of terms in an Add/Sub tree.
fn count_add_terms(ctx: &Context, expr: ExprId) -> usize {
    match ctx.get(expr) {
        Expr::Add(l, r) | Expr::Sub(l, r) => count_add_terms(ctx, *l) + count_add_terms(ctx, *r),
        Expr::Neg(e) => count_add_terms(ctx, *e),
        _ => 1,
    }
}
