use crate::expr_destructure::{as_add, as_div, as_mul, as_pow};
use crate::expr_extract::{
    extract_log_base_argument, extract_log_base_argument_relaxed_view,
    extract_log_base_argument_view,
};
use crate::expr_nary::MulView;
use crate::expr_predicates::is_e_constant_expr;
use crate::expr_rewrite::smart_mul;
use crate::perfect_square_support::{
    extract_square_root_of_term, rational_sqrt, try_match_perfect_square_trinomial,
};
use cas_ast::{BuiltinFn, Constant, Context, Expr, ExprId};
use num_traits::{One, Zero};
use std::cmp::Ordering;
use std::collections::HashMap;

/// Simplify `base^(log(base, x))` subterms when splitting exponent sums.
pub fn simplify_exp_log(context: &mut Context, base: ExprId, exp: ExprId) -> ExprId {
    if let Expr::Function(name, args) = context.get(exp) {
        if context.is_builtin(*name, BuiltinFn::Log) && args.len() == 2 {
            let log_base = args[0];
            let log_arg = args[1];
            if log_base == base {
                return log_arg;
            }
        }
    }
    context.add(Expr::Pow(base, exp))
}

/// Rewrite `e^(a+b)` into product form when at least one side is logarithmic:
/// - `e^(a+b) -> e^a * e^b`
/// - matching `e^(log(e,x)+k)` style terms will simplify to `x*e^k`.
pub fn try_rewrite_split_log_exponents_expr(ctx: &mut Context, expr: ExprId) -> Option<LogRewrite> {
    let (base, exp) = as_pow(ctx, expr)?;
    if !is_e_constant_expr(ctx, base) {
        return None;
    }

    let (lhs, rhs) = as_add(ctx, exp)?;
    if !(is_log(ctx, lhs) || is_log(ctx, rhs)) {
        return None;
    }

    let term1 = simplify_exp_log(ctx, base, lhs);
    let term2 = simplify_exp_log(ctx, base, rhs);
    let rewritten = smart_mul(ctx, term1, term2);
    Some(LogRewrite {
        rewritten,
        desc: "e^(a+b) -> e^a * e^b (log cancellation)",
    })
}

/// Detect whether expression is a log/ln call (possibly nested in a product).
pub fn is_log(ctx: &Context, expr: ExprId) -> bool {
    if let Expr::Function(name, _) = ctx.get(expr) {
        if let Some(b) = ctx.builtin_of(*name) {
            return b == BuiltinFn::Log || b == BuiltinFn::Ln;
        }
    }
    if let Expr::Mul(l, r) = ctx.get(expr) {
        return is_log(ctx, *l) || is_log(ctx, *r);
    }
    false
}

/// Normalize expression to `(core, exponent)` form:
/// - `a` => `(a, 1)`
/// - `a^m` => `(a, m)`
/// - `1/a` => `(a, -1)`
pub fn normalize_to_power(ctx: &mut Context, expr: ExprId) -> (ExprId, ExprId) {
    match ctx.get(expr) {
        Expr::Pow(base, exp) => (*base, *exp),
        Expr::Div(num, den) => {
            let (num, den) = (*num, *den);
            if matches!(ctx.get(num), Expr::Number(n) if n.is_one()) {
                let neg_one = ctx.num(-1);
                (den, neg_one)
            } else {
                let one = ctx.num(1);
                (expr, one)
            }
        }
        _ => {
            let one = ctx.num(1);
            (expr, one)
        }
    }
}

/// Count multiplicative factors in a flattened multiplication tree.
pub fn count_mul_factors(ctx: &Context, expr: ExprId) -> u32 {
    match ctx.get(expr) {
        Expr::Mul(a, b) => count_mul_factors(ctx, *a) + count_mul_factors(ctx, *b),
        _ => 1,
    }
}

/// Collect multiplicative factors in left-to-right order from a multiplication tree.
pub fn collect_mul_factors(ctx: &Context, expr: ExprId) -> Vec<ExprId> {
    match ctx.get(expr) {
        Expr::Mul(a, b) => {
            let mut factors = collect_mul_factors(ctx, *a);
            factors.extend(collect_mul_factors(ctx, *b));
            factors
        }
        _ => vec![expr],
    }
}

/// Estimate how many terms would be generated by log expansion.
/// Returns `(base_terms, generated_terms, pow_exp_if_applicable)`.
pub fn estimate_log_terms(ctx: &Context, arg: ExprId) -> Option<(u32, u32, Option<u32>)> {
    match ctx.get(arg) {
        Expr::Mul(_, _) => {
            let factors = count_mul_factors(ctx, arg);
            if factors <= 1 {
                return None;
            }
            Some((factors, factors, None))
        }
        Expr::Div(num, den) => {
            let num_factors = count_mul_factors(ctx, *num);
            let den_factors = count_mul_factors(ctx, *den);
            let total = num_factors + den_factors;
            if total <= 1 {
                return None;
            }
            Some((total, total, None))
        }
        Expr::Pow(_, exp) => {
            if let Expr::Number(n) = ctx.get(*exp) {
                if n.is_integer() {
                    let exp_i64: i64 = n.to_integer().try_into().ok()?;
                    if exp_i64 > 0 {
                        let exp_u32 = exp_i64 as u32;
                        return Some((1, 1, Some(exp_u32)));
                    }
                }
            }
            None
        }
        _ => None,
    }
}

/// Evaluate `log_base(val)` as a rational number using prime factorization.
///
/// Returns `Some(ratio)` when both `base` and `val` are powers of the same
/// underlying prime support.
pub fn eval_log_rational(
    base: &num_bigint::BigInt,
    val: &num_bigint::BigInt,
) -> Option<num_rational::BigRational> {
    use num_bigint::BigInt;
    use num_rational::BigRational;
    use num_traits::{One, Signed, Zero};

    // Guard: base > 1, val > 0
    let one = BigInt::one();
    if base <= &one || val.is_zero() || val.is_negative() || base.is_negative() {
        return None;
    }

    // Special case: val = 1 => log_b(1) = 0
    if val.is_one() {
        return Some(BigRational::zero());
    }

    // Special case: base == val => log_b(b) = 1
    if base == val {
        return Some(BigRational::one());
    }

    let fb = prime_exponent_map(base);
    let fv = prime_exponent_map(val);

    if fb.keys().collect::<std::collections::HashSet<_>>()
        != fv.keys().collect::<std::collections::HashSet<_>>()
    {
        return None;
    }

    let mut ratio: Option<BigRational> = None;
    for (prime, exp_base) in &fb {
        let exp_val = fv.get(prime)?;
        if *exp_base == 0 {
            return None;
        }
        let r = BigRational::new(BigInt::from(*exp_val), BigInt::from(*exp_base));
        match &ratio {
            None => ratio = Some(r),
            Some(prev) if *prev == r => {}
            _ => return None,
        }
    }

    ratio
}

/// Rewrite/evaluate simple logarithm identities:
/// - `log(b, 1) -> 0`, `log(b, 0) -> -infinity`, `log(b, neg) -> undefined`
/// - numeric ratio evaluation when both base/arg are compatible integer powers
/// - `log(b, b) -> 1`
/// - `log(b, b^n) -> n` (numeric exponent)
/// - `log(b, x^y) -> y*log(b, x)` (non-inverse case; may require positivity assumption)
///
/// This function is purely structural/numeric and does not apply domain policy.
/// The caller is responsible for attaching assumption/require events.
pub fn try_rewrite_evaluate_log_expr(
    ctx: &mut Context,
    expr: ExprId,
) -> Option<EvaluateLogRewrite> {
    let (base, arg) = extract_log_base_argument(ctx, expr)?;

    if let Expr::Number(n) = ctx.get(arg) {
        let n = n.clone();
        if n.is_one() {
            let rewritten = ctx.num(0);
            return Some(EvaluateLogRewrite {
                rewritten,
                desc: "log(b, 1) = 0".to_string(),
                assume_positive_base: None,
            });
        }
        if n.is_zero() {
            let inf = ctx.add(Expr::Constant(Constant::Infinity));
            let rewritten = ctx.add(Expr::Neg(inf));
            return Some(EvaluateLogRewrite {
                rewritten,
                desc: "log(b, 0) = -infinity".to_string(),
                assume_positive_base: None,
            });
        }
        if n < num_rational::BigRational::zero() {
            let rewritten = ctx.add(Expr::Constant(Constant::Undefined));
            return Some(EvaluateLogRewrite {
                rewritten,
                desc: "log(b, neg) = undefined".to_string(),
                assume_positive_base: None,
            });
        }

        if let Expr::Number(b) = ctx.get(base) {
            let b = b.clone();
            if b.is_integer() && n.is_integer() {
                let b_int = b.to_integer();
                let n_int = n.to_integer();
                if let Some(ratio) = eval_log_rational(&b_int, &n_int) {
                    let rewritten = ctx.add(Expr::Number(ratio.clone()));
                    return Some(EvaluateLogRewrite {
                        rewritten,
                        desc: format!("log({}, {}) = {}", b, n, ratio),
                        assume_positive_base: None,
                    });
                }
            }
        }
    }

    if base == arg || ctx.get(base) == ctx.get(arg) {
        let rewritten = ctx.num(1);
        return Some(EvaluateLogRewrite {
            rewritten,
            desc: "log(b, b) = 1".to_string(),
            assume_positive_base: None,
        });
    }

    let Expr::Pow(p_base, p_exp) = ctx.get(arg) else {
        return None;
    };
    let (p_base, p_exp) = (*p_base, *p_exp);
    let is_inverse_composition =
        p_base == base || cas_ast::ordering::compare_expr(ctx, p_base, base) == Ordering::Equal;

    if is_inverse_composition {
        if matches!(ctx.get(p_exp), Expr::Number(_)) {
            return Some(EvaluateLogRewrite {
                rewritten: p_exp,
                desc: "log(b, b^n) = n".to_string(),
                assume_positive_base: None,
            });
        }
        return None;
    }

    let is_even_integer = match ctx.get(p_exp) {
        Expr::Number(n) if n.is_integer() => {
            let int_val = n.to_integer();
            let two: num_bigint::BigInt = 2.into();
            (&int_val % &two) == 0.into() && int_val != 0.into()
        }
        _ => false,
    };
    if is_even_integer {
        return None;
    }

    let log_inner = make_log_expr(ctx, base, p_base);
    let rewritten = smart_mul(ctx, p_exp, log_inner);
    Some(EvaluateLogRewrite {
        rewritten,
        desc: "log(b, x^y) = y * log(b, x)".to_string(),
        assume_positive_base: Some(p_base),
    })
}

/// Compute prime factorization map `prime -> exponent`.
pub fn prime_exponent_map(n: &num_bigint::BigInt) -> HashMap<num_bigint::BigInt, u32> {
    use num_bigint::BigInt;
    use num_integer::Integer;
    use num_traits::{One, Signed, Zero};

    let mut result = HashMap::new();
    let mut n = n.abs();
    let one = BigInt::one();

    if n <= one {
        return result;
    }

    let mut count_2 = 0u32;
    while n.is_even() {
        count_2 += 1;
        n /= 2;
    }
    if count_2 > 0 {
        result.insert(BigInt::from(2), count_2);
    }

    let mut d = BigInt::from(3);
    while &d * &d <= n {
        let mut count = 0u32;
        while (&n % &d).is_zero() {
            count += 1;
            n /= &d;
        }
        if count > 0 {
            result.insert(d.clone(), count);
        }
        d += 2;
    }

    if n > one {
        result.insert(n, 1);
    }

    result
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LogRewrite {
    pub rewritten: ExprId,
    pub desc: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LnEProductRewrite {
    pub rewritten: ExprId,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LnEDivRewriteKind {
    XOverE,
    EOverX,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LnEDivRewrite {
    pub rewritten: ExprId,
    pub kind: LnEDivRewriteKind,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LogContractionRewrite {
    pub rewritten: ExprId,
    pub kind: LogContractionRewriteKind,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LogContractionRewriteKind {
    Add,
    Sub,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LogChainProductRewrite {
    pub rewritten: ExprId,
    pub kind: LogChainProductRewriteKind,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LogChainProductRewriteKind {
    Telescoping,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ExponentialLogInverseRewrite {
    pub rewritten: ExprId,
    pub positive_subject: ExprId,
    pub desc: &'static str,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LogPowerBaseNumericRewrite {
    pub rewritten: ExprId,
    pub base_core: ExprId,
    pub base_expr: ExprId,
    pub desc: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LogAutoExpandMode {
    Strict,
    Generic,
    Assume,
}

/// Derive [`LogAutoExpandMode`] from generic mode flags.
pub fn log_auto_expand_mode_from_flags(assume_mode: bool, strict_mode: bool) -> LogAutoExpandMode {
    if assume_mode {
        LogAutoExpandMode::Assume
    } else if strict_mode {
        LogAutoExpandMode::Strict
    } else {
        LogAutoExpandMode::Generic
    }
}

/// Generic mode is the only mode that consults implicit-domain inheritance
/// during auto log expansion.
pub fn log_auto_expand_needs_implicit_domain(mode: LogAutoExpandMode) -> bool {
    matches!(mode, LogAutoExpandMode::Generic)
}

/// Generic mode is the only mode that emits blocked hints for auto log expansion.
pub fn log_auto_expand_emits_blocked_hint(mode: LogAutoExpandMode) -> bool {
    matches!(mode, LogAutoExpandMode::Generic)
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LogAutoExpandPositivityPlan {
    AllowNoAssumptions,
    AllowWithAssumptions(Vec<ExprId>),
    Blocked { factor: ExprId },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LogExpInversePolicyMode {
    Strict,
    Generic,
    Assume,
}

/// Derive [`LogExpInversePolicyMode`] from generic mode flags.
pub fn log_exp_inverse_policy_mode_from_flags(
    assume_mode: bool,
    strict_mode: bool,
) -> LogExpInversePolicyMode {
    if assume_mode {
        LogExpInversePolicyMode::Assume
    } else if strict_mode {
        LogExpInversePolicyMode::Strict
    } else {
        LogExpInversePolicyMode::Generic
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LogExpInversePolicyPlan {
    Block,
    Rewrite { assume_positive_base: bool },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ExponentialLogInversePolicyPlan {
    Block,
    Rewrite { require_positive_subject: bool },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LogPowerBasePolicyPlan {
    Block,
    Rewrite {
        require_positive_base: bool,
        require_nonzero_base_minus_one: bool,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LogExpInverseMatch {
    Numeric {
        rewritten: ExprId,
        desc: &'static str,
    },
    Symbolic {
        base: ExprId,
        exponent: ExprId,
    },
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EvaluateLogRewrite {
    pub rewritten: ExprId,
    pub desc: String,
    pub assume_positive_base: Option<ExprId>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ExpandedLogAssumptionPlan {
    pub rewritten: ExprId,
    pub assumed_positive: Vec<ExprId>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LogMulDivExpansionRewrite {
    pub rewritten: ExprId,
    pub positive_lhs: ExprId,
    pub positive_rhs: ExprId,
    pub desc: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LogPerfectSquareRewrite {
    pub rewritten: ExprId,
    pub desc: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LogEvenPowerAbsPlan {
    pub inner_base: ExprId,
    pub exponent: ExprId,
    pub abs_inner_base: ExprId,
    pub with_abs_rewrite: ExprId,
    pub without_abs_rewrite: ExprId,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LogAbsPowerRewrite {
    pub rewritten: ExprId,
    pub inner_subject: ExprId,
    pub desc: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LogAbsSimplifyRewrite {
    pub rewritten: ExprId,
    pub inner_subject: ExprId,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LogAbsSimplifyPolicyPlan {
    Block,
    Rewrite {
        assume_positive_subject: bool,
        desc: &'static str,
    },
}

/// Plan positivity handling for auto-expanding logarithms.
///
/// The caller provides positivity predicates:
/// - `is_proven_positive`: algebraic proof oracle
/// - `is_implied_positive`: inherited-domain implication oracle
///
/// Behavior by mode:
/// - Strict: every factor must be proven positive
/// - Generic: every factor must be proven OR implied positive
/// - Assume: expansion is allowed, returning factors that need assumptions
pub fn plan_log_auto_expand_positivity(
    ctx: &Context,
    arg: ExprId,
    mode: LogAutoExpandMode,
    mut is_proven_positive: impl FnMut(ExprId) -> bool,
    mut is_implied_positive: impl FnMut(ExprId) -> bool,
) -> LogAutoExpandPositivityPlan {
    let factors = collect_mul_factors(ctx, arg);

    match mode {
        LogAutoExpandMode::Strict => {
            for factor in factors {
                if !is_proven_positive(factor) {
                    return LogAutoExpandPositivityPlan::Blocked { factor };
                }
            }
            LogAutoExpandPositivityPlan::AllowNoAssumptions
        }
        LogAutoExpandMode::Generic => {
            for factor in factors {
                if is_proven_positive(factor) || is_implied_positive(factor) {
                    continue;
                }
                return LogAutoExpandPositivityPlan::Blocked { factor };
            }
            LogAutoExpandPositivityPlan::AllowNoAssumptions
        }
        LogAutoExpandMode::Assume => {
            let mut assumptions = Vec::new();
            for factor in factors {
                if !is_proven_positive(factor) {
                    assumptions.push(factor);
                }
            }
            if assumptions.is_empty() {
                LogAutoExpandPositivityPlan::AllowNoAssumptions
            } else {
                LogAutoExpandPositivityPlan::AllowWithAssumptions(assumptions)
            }
        }
    }
}

/// Plan domain policy for symbolic `log(b, b^x) -> x` rewrites.
///
/// Inputs are fully-decided booleans from the engine side so this function stays
/// domain-agnostic and reusable.
pub fn plan_log_exp_inverse_symbolic_policy(
    mode: LogExpInversePolicyMode,
    complex_enabled: bool,
    is_e_base: bool,
    base_positive_proven: bool,
    base_is_one: bool,
) -> LogExpInversePolicyPlan {
    if complex_enabled {
        return LogExpInversePolicyPlan::Block;
    }

    if is_e_base {
        return LogExpInversePolicyPlan::Rewrite {
            assume_positive_base: false,
        };
    }

    if !base_positive_proven {
        return match mode {
            LogExpInversePolicyMode::Strict | LogExpInversePolicyMode::Generic => {
                LogExpInversePolicyPlan::Block
            }
            LogExpInversePolicyMode::Assume => LogExpInversePolicyPlan::Rewrite {
                assume_positive_base: true,
            },
        };
    }

    if base_is_one {
        return LogExpInversePolicyPlan::Block;
    }

    LogExpInversePolicyPlan::Rewrite {
        assume_positive_base: false,
    }
}

/// Plan domain policy for `b^log(b, x)` family rewrites.
pub fn plan_exponential_log_inverse_policy(
    mode: LogExpInversePolicyMode,
    positive_subject_proven: bool,
) -> ExponentialLogInversePolicyPlan {
    match mode {
        LogExpInversePolicyMode::Strict if !positive_subject_proven => {
            ExponentialLogInversePolicyPlan::Block
        }
        _ => ExponentialLogInversePolicyPlan::Rewrite {
            require_positive_subject: !positive_subject_proven,
        },
    }
}

/// Plan domain policy for numeric `log(a^m, a^n) -> n/m` rewrites.
pub fn plan_log_power_base_numeric_policy(
    mode: LogExpInversePolicyMode,
    complex_enabled: bool,
    base_positive_proven: bool,
    base_is_one: bool,
) -> LogPowerBasePolicyPlan {
    if complex_enabled {
        return LogPowerBasePolicyPlan::Block;
    }

    match mode {
        LogExpInversePolicyMode::Strict => {
            if !base_positive_proven || base_is_one {
                LogPowerBasePolicyPlan::Block
            } else {
                LogPowerBasePolicyPlan::Rewrite {
                    require_positive_base: false,
                    require_nonzero_base_minus_one: true,
                }
            }
        }
        LogExpInversePolicyMode::Generic => LogPowerBasePolicyPlan::Rewrite {
            require_positive_base: false,
            require_nonzero_base_minus_one: true,
        },
        LogExpInversePolicyMode::Assume => LogPowerBasePolicyPlan::Rewrite {
            require_positive_base: !base_positive_proven,
            require_nonzero_base_minus_one: true,
        },
    }
}

/// Build canonical log expression:
/// - `base == sentinel_log10` => `log(arg)`
/// - `base == e` => `ln(arg)`
/// - otherwise => `log(base, arg)`
pub fn make_log_expr(ctx: &mut Context, base: ExprId, arg: ExprId) -> ExprId {
    // Sentinel reserved by engine layer for base-10 log.
    let sentinel_log10 = ExprId::from_raw(u32::MAX - 1);
    if base == sentinel_log10 {
        return ctx.call_builtin(BuiltinFn::Log, vec![arg]);
    }
    if is_e_constant_expr(ctx, base) {
        ctx.call_builtin(BuiltinFn::Ln, vec![arg])
    } else {
        ctx.call_builtin(BuiltinFn::Log, vec![base, arg])
    }
}

/// Sentinel used by legacy engine log rules to represent the `ln` base.
#[inline]
pub fn ln_base_sentinel() -> ExprId {
    ExprId::from_raw(u32::MAX)
}

/// Extract `(base, argument)` from a log expression.
///
/// Returns:
/// - `(ln_base_sentinel(), arg)` for `ln(arg)`
/// - `(base, arg)` for `log(base, arg)`
pub fn try_extract_log_parts(ctx: &Context, expr: ExprId) -> Option<(ExprId, ExprId)> {
    let Expr::Function(fn_id, args) = ctx.get(expr) else {
        return None;
    };

    match ctx.builtin_of(*fn_id) {
        Some(BuiltinFn::Ln) if args.len() == 1 => Some((ln_base_sentinel(), args[0])),
        Some(BuiltinFn::Log) if args.len() == 2 => Some((args[0], args[1])),
        _ => None,
    }
}

/// Compare two expressions for logarithm-base matching semantics.
///
/// Special handling:
/// - `ExprId::from_raw(u32::MAX)` is treated as ln-base sentinel and matches `e`.
pub fn exprs_match_for_logs(ctx: &Context, e1: ExprId, e2: ExprId) -> bool {
    let sentinel = ln_base_sentinel();

    if e1 == sentinel {
        return is_e_constant_expr(ctx, e2);
    }
    if e2 == sentinel {
        return is_e_constant_expr(ctx, e1);
    }

    if e1 == e2 {
        return true;
    }

    cas_ast::ordering::compare_expr(ctx, e1, e2) == Ordering::Equal
}

/// Compare log bases with ln-sentinel compatibility.
pub fn bases_equal_for_logs(ctx: &Context, base_l: ExprId, base_r: ExprId) -> bool {
    let sentinel = ln_base_sentinel();

    if base_l == sentinel && base_r == sentinel {
        return true;
    }
    if base_l == sentinel {
        return is_e_constant_expr(ctx, base_r);
    }
    if base_r == sentinel {
        return is_e_constant_expr(ctx, base_l);
    }

    if base_l == base_r {
        return true;
    }

    cas_ast::ordering::compare_expr(ctx, base_l, base_r) == Ordering::Equal
}

/// Rewrite `ln(e*x)` or `ln(x*e)` to `1 + ln(x)`.
pub fn try_rewrite_ln_e_product_expr(ctx: &mut Context, expr: ExprId) -> Option<LnEProductRewrite> {
    let Expr::Function(fn_id, args) = ctx.get(expr) else {
        return None;
    };
    let fn_id = *fn_id;
    let args = args.clone();
    if ctx.builtin_of(fn_id) != Some(BuiltinFn::Ln) || args.len() != 1 {
        return None;
    }
    let arg = args[0];

    let Expr::Mul(l, r) = ctx.get(arg) else {
        return None;
    };
    let (l, r) = (*l, *r);
    let l_is_e = is_e_constant_expr(ctx, l);
    let r_is_e = is_e_constant_expr(ctx, r);

    let x = if l_is_e {
        Some(r)
    } else if r_is_e {
        Some(l)
    } else {
        None
    }?;

    let one = ctx.num(1);
    let ln_x = ctx.call_builtin(BuiltinFn::Ln, vec![x]);
    let rewritten = ctx.add(Expr::Add(one, ln_x));
    Some(LnEProductRewrite { rewritten })
}

/// Rewrite:
/// - `ln(x/e)` -> `ln(x) - 1`
/// - `ln(e/x)` -> `1 - ln(x)`
pub fn try_rewrite_ln_e_div_expr(ctx: &mut Context, expr: ExprId) -> Option<LnEDivRewrite> {
    let Expr::Function(fn_id, args) = ctx.get(expr) else {
        return None;
    };
    let fn_id = *fn_id;
    let args = args.clone();
    if ctx.builtin_of(fn_id) != Some(BuiltinFn::Ln) || args.len() != 1 {
        return None;
    }
    let arg = args[0];

    let Expr::Div(num, den) = ctx.get(arg) else {
        return None;
    };
    let (num, den) = (*num, *den);
    let num_is_e = is_e_constant_expr(ctx, num);
    let den_is_e = is_e_constant_expr(ctx, den);

    if den_is_e && !num_is_e {
        let ln_x = ctx.call_builtin(BuiltinFn::Ln, vec![num]);
        let one = ctx.num(1);
        let rewritten = ctx.add(Expr::Sub(ln_x, one));
        return Some(LnEDivRewrite {
            rewritten,
            kind: LnEDivRewriteKind::XOverE,
        });
    }

    if num_is_e && !den_is_e {
        let one = ctx.num(1);
        let ln_x = ctx.call_builtin(BuiltinFn::Ln, vec![den]);
        let rewritten = ctx.add(Expr::Sub(one, ln_x));
        return Some(LnEDivRewrite {
            rewritten,
            kind: LnEDivRewriteKind::EOverX,
        });
    }

    None
}

/// Contract pairwise logarithm additions/subtractions:
/// - `ln(a) + ln(b) -> ln(a*b)`
/// - `ln(a) - ln(b) -> ln(a/b)`
/// - `log(b, x) + log(b, y) -> log(b, x*y)` for equal bases
/// - `log(b, x) - log(b, y) -> log(b, x/y)` for equal bases
pub fn try_rewrite_log_contraction_expr(
    ctx: &mut Context,
    expr: ExprId,
) -> Option<LogContractionRewrite> {
    match ctx.get(expr) {
        Expr::Add(lhs, rhs) => {
            let (lhs, rhs) = (*lhs, *rhs);
            let (base_l, arg_l) = try_extract_log_parts(ctx, lhs)?;
            let (base_r, arg_r) = try_extract_log_parts(ctx, rhs)?;
            if !bases_equal_for_logs(ctx, base_l, base_r) {
                return None;
            }

            let product = ctx.add(Expr::Mul(arg_l, arg_r));
            let rewritten = if base_l == ln_base_sentinel() {
                ctx.call_builtin(BuiltinFn::Ln, vec![product])
            } else {
                make_log_expr(ctx, base_l, product)
            };
            Some(LogContractionRewrite {
                rewritten,
                kind: LogContractionRewriteKind::Add,
            })
        }
        Expr::Sub(lhs, rhs) => {
            let (lhs, rhs) = (*lhs, *rhs);
            let (base_l, arg_l) = try_extract_log_parts(ctx, lhs)?;
            let (base_r, arg_r) = try_extract_log_parts(ctx, rhs)?;
            if !bases_equal_for_logs(ctx, base_l, base_r) {
                return None;
            }

            let quotient = ctx.add(Expr::Div(arg_l, arg_r));
            let rewritten = if base_l == ln_base_sentinel() {
                ctx.call_builtin(BuiltinFn::Ln, vec![quotient])
            } else {
                make_log_expr(ctx, base_l, quotient)
            };
            Some(LogContractionRewrite {
                rewritten,
                kind: LogContractionRewriteKind::Sub,
            })
        }
        _ => None,
    }
}

/// Expand one-step logarithm product/quotient:
/// - `log(b, x*y) -> log(b, x) + log(b, y)`
/// - `log(b, x/y) -> log(b, x) - log(b, y)`
///
/// Returns both factors that require positivity checks (`x`, `y`) so caller
/// can apply domain-policy/assumption handling outside this helper.
pub fn try_rewrite_log_mul_div_expansion_expr(
    ctx: &mut Context,
    expr: ExprId,
) -> Option<LogMulDivExpansionRewrite> {
    let (base, arg) = extract_log_base_argument(ctx, expr)?;

    if let Some((lhs, rhs)) = as_mul(ctx, arg) {
        let log_lhs = make_log_expr(ctx, base, lhs);
        let log_rhs = make_log_expr(ctx, base, rhs);
        let rewritten = ctx.add(Expr::Add(log_lhs, log_rhs));
        return Some(LogMulDivExpansionRewrite {
            rewritten,
            positive_lhs: lhs,
            positive_rhs: rhs,
            desc: "log(b, x*y) = log(b, x) + log(b, y)",
        });
    }

    if let Some((num, den)) = as_div(ctx, arg) {
        let log_num = make_log_expr(ctx, base, num);
        let log_den = make_log_expr(ctx, base, den);
        let rewritten = ctx.add(Expr::Sub(log_num, log_den));
        return Some(LogMulDivExpansionRewrite {
            rewritten,
            positive_lhs: num,
            positive_rhs: den,
            desc: "log(b, x/y) = log(b, x) - log(b, y)",
        });
    }

    None
}

/// Rewrite perfect-square logarithm arguments:
/// - `ln((A ± B)^2) -> 2*ln(|A ± B|)`
/// - `log(base, (A ± B)^2) -> 2*log(base, |A ± B|)`
///
/// Includes detectors for:
/// - coefficient-bearing quadratic trinomials with discriminant 0
/// - AST-level perfect-square trinomial matching
/// - even powers, monomial squares, and quotient of squares
pub fn try_rewrite_log_perfect_square_expr(
    ctx: &mut Context,
    expr: ExprId,
) -> Option<LogPerfectSquareRewrite> {
    let fn_id = match ctx.get(expr) {
        Expr::Function(fn_id, _) => *fn_id,
        _ => return None,
    };

    let (log_base, arg) = match ctx.builtin_of(fn_id) {
        Some(BuiltinFn::Ln) | Some(BuiltinFn::Log) => extract_log_base_argument(ctx, expr)?,
        _ => return None,
    };

    let build_result = |ctx: &mut Context,
                        factor: ExprId,
                        log_base: ExprId,
                        desc: &'static str|
     -> Option<LogPerfectSquareRewrite> {
        let abs_factor = ctx.call_builtin(BuiltinFn::Abs, vec![factor]);
        let log_inner = make_log_expr(ctx, log_base, abs_factor);
        let two = ctx.num(2);
        let rewritten = ctx.add(Expr::Mul(two, log_inner));
        Some(LogPerfectSquareRewrite { rewritten, desc })
    };

    if matches!(ctx.get(arg), Expr::Add(_, _) | Expr::Sub(_, _)) {
        let vars = cas_ast::collect_variables(ctx, arg);
        if vars.len() == 1 {
            let var = vars.iter().next()?;
            if let Ok(poly) = crate::polynomial::Polynomial::from_expr(ctx, arg, var) {
                if poly.degree() == 2 && poly.coeffs.len() >= 3 {
                    let pa = poly.coeffs.get(2).cloned();
                    let pb = poly.coeffs.get(1).cloned();
                    let pc = poly.coeffs.first().cloned();

                    if let (Some(pa), Some(pb), Some(pc)) = (pa, pb, pc) {
                        let four = num_rational::BigRational::from_integer(4.into());
                        let discriminant = pb.clone() * pb.clone() - four * pa.clone() * pc.clone();

                        if discriminant.is_zero() {
                            if let Some(d) = rational_sqrt(&pa) {
                                let two_r = num_rational::BigRational::from_integer(2.into());
                                let e = if d.is_zero() {
                                    rational_sqrt(&pc)
                                        .unwrap_or_else(num_rational::BigRational::zero)
                                } else {
                                    pb / (two_r * d.clone())
                                };

                                let var_expr = ctx.var(var);
                                let d_expr = ctx.add(Expr::Number(d.clone()));
                                let e_expr = ctx.add(Expr::Number(e.clone()));
                                let one = num_rational::BigRational::from_integer(1.into());

                                let dx = if d == one {
                                    var_expr
                                } else {
                                    smart_mul(ctx, d_expr, var_expr)
                                };

                                let linear = if e.is_zero() {
                                    dx
                                } else {
                                    ctx.add(Expr::Add(dx, e_expr))
                                };

                                return build_result(
                                    ctx,
                                    linear,
                                    log_base,
                                    "ln((A+B)^2) = 2·ln(|A+B|)",
                                );
                            }
                        }
                    }
                }
            }
        }

        if let Some((a, b, is_sub)) = try_match_perfect_square_trinomial(ctx, arg) {
            let factor = if is_sub {
                ctx.add(Expr::Sub(a, b))
            } else {
                ctx.add(Expr::Add(a, b))
            };
            let desc = if is_sub {
                "ln((A-B)^2) = 2·ln(|A-B|)"
            } else {
                "ln((A+B)^2) = 2·ln(|A+B|)"
            };
            return build_result(ctx, factor, log_base, desc);
        }
    }

    if let Expr::Pow(p_base, p_exp) = ctx.get(arg) {
        let (p_base, p_exp) = (*p_base, *p_exp);
        if cas_ast::ordering::compare_expr(ctx, p_base, log_base) == Ordering::Equal {
            return None;
        }

        if let Expr::Number(n) = ctx.get(p_exp) {
            let n = n.clone();
            if n.is_integer() {
                let int_val = n.to_integer();
                let two_bi: num_bigint::BigInt = 2.into();
                if &int_val % &two_bi == 0.into() && int_val > 0.into() {
                    let half = &int_val / &two_bi;
                    let half_rat = num_rational::BigRational::from_integer(half.clone());
                    let factor = if half == 1.into() {
                        p_base
                    } else {
                        let half_id = ctx.add(Expr::Number(half_rat));
                        ctx.add(Expr::Pow(p_base, half_id))
                    };
                    return build_result(ctx, factor, log_base, "ln(x^(2k)) = 2·ln(|x^k|)");
                }
            }
        }
    }

    if let Expr::Mul(_, _) = ctx.get(arg) {
        if let Some(factor) = extract_square_root_of_term(ctx, arg) {
            return build_result(ctx, factor, log_base, "ln((c*x)^2) = 2·ln(|c*x|)");
        }
    }

    if let Expr::Div(num, den) = ctx.get(arg) {
        let (num, den) = (*num, *den);
        if let (Some(num_root), Some(den_root)) = (
            extract_square_root_of_term(ctx, num),
            extract_square_root_of_term(ctx, den),
        ) {
            let factor = ctx.add(Expr::Div(num_root, den_root));
            return build_result(ctx, factor, log_base, "ln(a^2/b^2) = 2·ln(|a/b|)");
        }
    }

    None
}

/// Plan `log(base, x^(even))` rewrite candidates:
/// - with absolute value: `even * log(base, |x|)`
/// - without absolute value: `even * log(base, x)`
///
/// Structural gates:
/// - argument must be a power with even integer exponent
/// - skip inverse compositions (`log(b, b^x)`)
/// - skip `ln(exp(...)^n)` to let inverse-exp rules fire first
pub fn try_plan_log_even_power_abs_expr(
    ctx: &mut Context,
    expr: ExprId,
) -> Option<LogEvenPowerAbsPlan> {
    let (base, arg) = extract_log_base_argument(ctx, expr)?;
    let (inner_base, exponent) = as_pow(ctx, arg)?;

    if cas_ast::ordering::compare_expr(ctx, inner_base, base) == Ordering::Equal {
        return None;
    }

    if is_e_constant_expr(ctx, base)
        && matches!(ctx.get(inner_base), Expr::Function(fname, _) if ctx.is_builtin(*fname, BuiltinFn::Exp))
    {
        return None;
    }

    let is_even_integer = match ctx.get(exponent) {
        Expr::Number(n) if n.is_integer() => {
            let int_val = n.to_integer();
            let two: num_bigint::BigInt = 2.into();
            (&int_val % &two) == 0.into() && int_val != 0.into()
        }
        _ => false,
    };
    if !is_even_integer {
        return None;
    }

    let abs_inner_base = ctx.call_builtin(BuiltinFn::Abs, vec![inner_base]);
    let with_abs_log = make_log_expr(ctx, base, abs_inner_base);
    let without_abs_log = make_log_expr(ctx, base, inner_base);

    Some(LogEvenPowerAbsPlan {
        inner_base,
        exponent,
        abs_inner_base,
        with_abs_rewrite: smart_mul(ctx, exponent, with_abs_log),
        without_abs_rewrite: smart_mul(ctx, exponent, without_abs_log),
    })
}

/// Rewrite `log(base, |u|^n)` with positive integer `n`:
/// - `log(base, |u|^n) -> n * log(base, |u|)`
///
/// Returns the inner subject `u` so caller can attach non-zero hints/requirements.
pub fn try_rewrite_log_abs_power_expr(
    ctx: &mut Context,
    expr: ExprId,
) -> Option<LogAbsPowerRewrite> {
    let (base, arg) = extract_log_base_argument(ctx, expr)?;
    let (pow_base, pow_exp) = as_pow(ctx, arg)?;

    let Expr::Function(abs_name, abs_args) = ctx.get(pow_base) else {
        return None;
    };
    if !ctx.is_builtin(*abs_name, BuiltinFn::Abs) || abs_args.len() != 1 {
        return None;
    }
    let inner_subject = abs_args[0];

    let is_positive_integer = match ctx.get(pow_exp) {
        Expr::Number(n) if n.is_integer() => {
            let int_val = n.to_integer();
            int_val > 0.into()
        }
        _ => false,
    };
    if !is_positive_integer {
        return None;
    }

    let log_abs = make_log_expr(ctx, base, pow_base);
    Some(LogAbsPowerRewrite {
        rewritten: smart_mul(ctx, pow_exp, log_abs),
        inner_subject,
        desc: "ln(|u|^n) = n·ln(|u|)",
    })
}

/// Rewrite `log(base, |x|)` / `ln(|x|)` into `log(base, x)` / `ln(x)`.
///
/// This is structural-only and does not enforce domain policy.
/// Callers should apply `plan_log_abs_simplify_policy` before committing rewrite.
pub fn try_rewrite_log_abs_simplify_expr(
    ctx: &mut Context,
    expr: ExprId,
) -> Option<LogAbsSimplifyRewrite> {
    let (base_opt, arg) = extract_log_base_argument_view(ctx, expr)?;

    let inner_subject = match ctx.get(arg) {
        Expr::Function(fn_id, args)
            if ctx.is_builtin(*fn_id, BuiltinFn::Abs) && args.len() == 1 =>
        {
            args[0]
        }
        _ => return None,
    };

    let rewritten = match base_opt {
        Some(base) => ctx.call_builtin(BuiltinFn::Log, vec![base, inner_subject]),
        None => ctx.call_builtin(BuiltinFn::Ln, vec![inner_subject]),
    };

    Some(LogAbsSimplifyRewrite {
        rewritten,
        inner_subject,
    })
}

/// Plan domain policy for simplifying `log(base, |x|)` / `ln(|x|)` to `log(base, x)` / `ln(x)`.
///
/// `complex_enabled`: true when value-domain is complex.
/// `positive_subject_proven`: true when positivity of `x` is proven.
pub fn plan_log_abs_simplify_policy(
    mode: LogExpInversePolicyMode,
    complex_enabled: bool,
    positive_subject_proven: bool,
) -> LogAbsSimplifyPolicyPlan {
    if complex_enabled {
        return if positive_subject_proven {
            LogAbsSimplifyPolicyPlan::Rewrite {
                assume_positive_subject: false,
                desc: "ln(|x|) = ln(x) for x > 0",
            }
        } else {
            LogAbsSimplifyPolicyPlan::Block
        };
    }

    match mode {
        LogExpInversePolicyMode::Assume => LogAbsSimplifyPolicyPlan::Rewrite {
            assume_positive_subject: true,
            desc: "ln(|x|) = ln(x) (assuming x > 0)",
        },
        LogExpInversePolicyMode::Strict | LogExpInversePolicyMode::Generic => {
            if positive_subject_proven {
                LogAbsSimplifyPolicyPlan::Rewrite {
                    assume_positive_subject: false,
                    desc: "ln(|x|) = ln(x) for x > 0",
                }
            } else {
                LogAbsSimplifyPolicyPlan::Block
            }
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LogEvenPowerPolicyPlan {
    Block,
    RewriteWithChain {
        chain_desc: &'static str,
        assume_positive_subject: bool,
    },
    RewriteWithAbsAssume {
        assume_positive_subject: bool,
    },
}

/// Plan policy for rewriting `log(base, x^(even))` through an absolute-value step:
/// - with chain: `even*log(base, |x|)` then `|x| -> x`
/// - without chain in Assume mode: keep `even*log(base, |x|)` with assumption
pub fn plan_log_even_power_policy(
    mode: LogExpInversePolicyMode,
    positive_subject_proven: bool,
    positive_subject_disproven: bool,
    in_requires: bool,
) -> LogEvenPowerPolicyPlan {
    let can_chain = match mode {
        LogExpInversePolicyMode::Strict | LogExpInversePolicyMode::Generic => {
            positive_subject_proven || in_requires
        }
        LogExpInversePolicyMode::Assume => !positive_subject_disproven,
    };

    if can_chain {
        let assume_positive_subject =
            !positive_subject_proven && !in_requires && mode == LogExpInversePolicyMode::Assume;
        let chain_desc = if positive_subject_proven || in_requires {
            "|x| = x for x > 0"
        } else {
            "|x| = x (assuming x > 0)"
        };
        return LogEvenPowerPolicyPlan::RewriteWithChain {
            chain_desc,
            assume_positive_subject,
        };
    }

    match mode {
        LogExpInversePolicyMode::Strict | LogExpInversePolicyMode::Generic => {
            LogEvenPowerPolicyPlan::Block
        }
        LogExpInversePolicyMode::Assume => LogEvenPowerPolicyPlan::RewriteWithAbsAssume {
            assume_positive_subject: true,
        },
    }
}

/// Whether looking up inherited positivity (`in_requires`) can change the
/// `log(x^(even))` policy outcome.
///
/// This allows callers to skip expensive implicit-domain inference when it
/// cannot affect the decision.
pub fn log_even_power_needs_requires_lookup(
    mode: LogExpInversePolicyMode,
    positive_subject_proven: bool,
    positive_subject_disproven: bool,
) -> bool {
    match mode {
        LogExpInversePolicyMode::Strict | LogExpInversePolicyMode::Generic => {
            !positive_subject_proven
        }
        LogExpInversePolicyMode::Assume => !positive_subject_proven && !positive_subject_disproven,
    }
}

/// Contract chain products of logarithms:
/// - `log(b, a) * log(a, c) -> log(b, c)`
pub fn try_rewrite_log_chain_product_expr(
    ctx: &mut Context,
    expr: ExprId,
) -> Option<LogChainProductRewrite> {
    if !matches!(ctx.get(expr), Expr::Mul(_, _)) {
        return None;
    }

    let factors: Vec<ExprId> = MulView::from_expr(ctx, expr).factors.into_iter().collect();
    let log_parts: Vec<Option<(ExprId, ExprId)>> = factors
        .iter()
        .map(|&factor| try_extract_log_parts(ctx, factor))
        .collect();

    for (i, log_i_opt) in log_parts.iter().enumerate() {
        let Some((base_i, arg_i)) = log_i_opt else {
            continue;
        };

        for (j, log_j_opt) in log_parts.iter().enumerate() {
            if i == j {
                continue;
            }
            let Some((base_j, arg_j)) = log_j_opt else {
                continue;
            };

            if !exprs_match_for_logs(ctx, *arg_i, *base_j) {
                continue;
            }

            let new_log = make_log_expr(ctx, *base_i, *arg_j);
            let mut product = new_log;
            let mut had_remaining = false;
            for (idx, &factor) in factors.iter().enumerate() {
                if idx == i || idx == j {
                    continue;
                }
                had_remaining = true;
                product = smart_mul(ctx, product, factor);
            }

            let rewritten = if had_remaining { product } else { new_log };
            return Some(LogChainProductRewrite {
                rewritten,
                kind: LogChainProductRewriteKind::Telescoping,
            });
        }
    }

    None
}

/// Rewrite exponential-log inverse compositions:
/// - `b^log(b, x) -> x`
/// - `b^(-log(b, x)) -> x^(-1)`
/// - `b^(c*log(b, x)) -> x^c`
///
/// Returns the rewritten expression plus the subject that must be positive for
/// domain-safe application (`x` above).
pub fn try_rewrite_exponential_log_inverse_expr(
    ctx: &mut Context,
    expr: ExprId,
) -> Option<ExponentialLogInverseRewrite> {
    let (base, exp) = as_pow(ctx, expr)?;

    let matches_base = |ctx: &Context, log_base: ExprId, target_base: ExprId| {
        cas_ast::ordering::compare_expr(ctx, log_base, target_base) == Ordering::Equal
    };

    if let Some((log_base, log_arg)) = extract_log_base_argument(ctx, exp) {
        if matches_base(ctx, log_base, base) {
            return Some(ExponentialLogInverseRewrite {
                rewritten: log_arg,
                positive_subject: log_arg,
                desc: "b^log(b, x) = x",
            });
        }
    }

    if let Expr::Neg(neg_inner) = ctx.get(exp) {
        let neg_inner = *neg_inner;
        if let Some((log_base, log_arg)) = extract_log_base_argument(ctx, neg_inner) {
            if matches_base(ctx, log_base, base) {
                let neg_one = ctx.num(-1);
                let rewritten = ctx.add(Expr::Pow(log_arg, neg_one));
                return Some(ExponentialLogInverseRewrite {
                    rewritten,
                    positive_subject: log_arg,
                    desc: "b^(-log(b, x)) = 1/x",
                });
            }
        }
    }

    let (lhs, rhs) = as_mul(ctx, exp)?;
    let try_side = |ctx: &mut Context,
                    target: ExprId,
                    coeff: ExprId,
                    target_base: ExprId|
     -> Option<ExponentialLogInverseRewrite> {
        let (log_base, log_arg) = extract_log_base_argument(ctx, target)?;
        if cas_ast::ordering::compare_expr(ctx, log_base, target_base) != Ordering::Equal {
            return None;
        }
        let rewritten = ctx.add(Expr::Pow(log_arg, coeff));
        Some(ExponentialLogInverseRewrite {
            rewritten,
            positive_subject: log_arg,
            desc: "b^(c*log(b, x)) = x^c",
        })
    };

    try_side(ctx, lhs, rhs, base).or_else(|| try_side(ctx, rhs, lhs, base))
}

/// Match `log(b, b^x)` / `ln(e^x)` inverse compositions.
///
/// Returns:
/// - `Numeric` when exponent is numeric (`log(b, b^n) -> n` always safe)
/// - `Symbolic` when exponent is symbolic and engine policy must decide.
pub fn try_match_log_exp_inverse_expr(
    ctx: &mut Context,
    expr: ExprId,
) -> Option<LogExpInverseMatch> {
    let (base, arg) = extract_log_base_argument(ctx, expr)?;
    let (pow_base, pow_exp) = as_pow(ctx, arg)?;

    if cas_ast::ordering::compare_expr(ctx, pow_base, base) != Ordering::Equal {
        return None;
    }

    if matches!(ctx.get(pow_exp), Expr::Number(_)) {
        Some(LogExpInverseMatch::Numeric {
            rewritten: pow_exp,
            desc: "log(b, b^n) = n",
        })
    } else {
        Some(LogExpInverseMatch::Symbolic {
            base,
            exponent: pow_exp,
        })
    }
}

/// Rewrite numeric `log(a^m, a^n) -> n/m`.
///
/// This only performs structural/numeric normalization and ratio computation.
/// Domain gating (`a>0`, `a!=1`, real/complex mode) remains engine policy.
pub fn try_rewrite_log_power_base_numeric_expr(
    ctx: &mut Context,
    expr: ExprId,
) -> Option<LogPowerBaseNumericRewrite> {
    let Expr::Function(fn_id, args) = ctx.get(expr) else {
        return None;
    };
    let fn_id = *fn_id;
    let args = args.clone();

    if ctx.builtin_of(fn_id) != Some(BuiltinFn::Log) || args.len() != 2 {
        return None;
    }
    let base = args[0];
    let arg = args[1];

    let (base_core, base_exp) = normalize_to_power(ctx, base);
    let (arg_core, arg_exp) = normalize_to_power(ctx, arg);

    if cas_ast::ordering::compare_expr(ctx, base_core, arg_core) != Ordering::Equal {
        return None;
    }

    let base_exp_is_one = matches!(ctx.get(base_exp), Expr::Number(n) if n.is_one());
    if base_exp_is_one {
        return None;
    }

    let Expr::Number(m) = ctx.get(base_exp) else {
        return None;
    };
    let Expr::Number(n) = ctx.get(arg_exp) else {
        return None;
    };

    let m = m.clone();
    let n = n.clone();
    if m.is_zero() {
        return None;
    }

    let result_ratio = n.clone() / m.clone();
    let rewritten = ctx.add(Expr::Number(result_ratio.clone()));
    let m_disp = m.clone();
    let n_disp = n.clone();
    let desc = format!(
        "log(a^{}, a^{}) = {}/{} = {}",
        m_disp, n_disp, n_disp, m_disp, result_ratio
    );

    Some(LogPowerBaseNumericRewrite {
        rewritten,
        base_core,
        base_expr: base,
        desc,
    })
}

/// Rewrite `x^(c/log(b, x))` patterns:
/// - `x^(c / log(b, x)) -> b^c`
/// - `x^(c / ln(x)) -> e^c`
/// - `x^(c * log(b, x)^-1) -> b^c`
pub fn try_rewrite_log_inverse_power_expr(ctx: &mut Context, expr: ExprId) -> Option<LogRewrite> {
    fn is_minus_one_power(ctx: &Context, expr: ExprId) -> bool {
        matches!(
            ctx.get(expr),
            Expr::Number(n)
                if n.is_integer()
                    && *n == num_rational::BigRational::from_integer((-1).into())
        )
    }

    let (base, exp) = as_pow(ctx, expr)?;

    let check_log_denom = |ctx: &Context, denom: ExprId| -> Option<Option<ExprId>> {
        let (log_base_opt, log_arg) = extract_log_base_argument_view(ctx, denom)?;
        if cas_ast::ordering::compare_expr(ctx, log_arg, base) == Ordering::Equal {
            Some(log_base_opt)
        } else {
            None
        }
    };

    let mut target_base_opt: Option<Option<ExprId>> = None;
    let mut coeff: Option<ExprId> = None;

    if let Some((num, den)) = as_div(ctx, exp) {
        if let Some(base_opt) = check_log_denom(ctx, den) {
            target_base_opt = Some(base_opt);
            coeff = Some(num);
        }
    } else if let Some((lhs, rhs)) = as_mul(ctx, exp) {
        if let Some((den, den_exp)) = as_pow(ctx, rhs) {
            if is_minus_one_power(ctx, den_exp) {
                if let Some(base_opt) = check_log_denom(ctx, den) {
                    target_base_opt = Some(base_opt);
                    coeff = Some(lhs);
                }
            }
        }

        if target_base_opt.is_none() {
            if let Some((den, den_exp)) = as_pow(ctx, lhs) {
                if is_minus_one_power(ctx, den_exp) {
                    if let Some(base_opt) = check_log_denom(ctx, den) {
                        target_base_opt = Some(base_opt);
                        coeff = Some(rhs);
                    }
                }
            }
        }
    } else if let Some((den, den_exp)) = as_pow(ctx, exp) {
        if is_minus_one_power(ctx, den_exp) {
            if let Some(base_opt) = check_log_denom(ctx, den) {
                target_base_opt = Some(base_opt);
                coeff = Some(ctx.num(1));
            }
        }
    }

    let (base_opt, c) = (target_base_opt?, coeff?);
    let target_base = base_opt.unwrap_or_else(|| ctx.add(Expr::Constant(Constant::E)));
    let rewritten = ctx.add(Expr::Pow(target_base, c));
    Some(LogRewrite {
        rewritten,
        desc: "x^(c/log(b, x)) = b^c",
    })
}

/// Expand logarithm arguments for auto-expand workflows:
/// - `log(b, a*b*c) -> log(b,a) + log(b,b) + log(b,c)`
/// - `log(b, a/b) -> log(b,a) - log(b,b)`
/// - `log(b, u^n) -> n*log(b,u)`
pub fn try_expand_log_auto_rule_expr(
    ctx: &mut Context,
    original: ExprId,
    arg: ExprId,
) -> Option<LogRewrite> {
    let (base_opt, _) = extract_log_base_argument_relaxed_view(ctx, original)?;
    let base = match base_opt {
        Some(base) => base,
        None => match ctx.get(original) {
            Expr::Function(fn_id, _) if ctx.is_builtin(*fn_id, BuiltinFn::Ln) => {
                ctx.add(Expr::Constant(Constant::E))
            }
            Expr::Function(fn_id, _) if ctx.is_builtin(*fn_id, BuiltinFn::Log) => {
                // `log(x)` base-10 sentinel used by engine/parser bridge.
                ExprId::from_raw(u32::MAX - 1)
            }
            _ => return None,
        },
    };

    match ctx.get(arg) {
        Expr::Mul(_, _) => {
            let factors = collect_mul_factors(ctx, arg);
            if factors.len() <= 1 {
                return None;
            }

            let mut sum = make_log_expr(ctx, base, factors[0]);
            for &factor in &factors[1..] {
                let log_factor = make_log_expr(ctx, base, factor);
                sum = ctx.add(Expr::Add(sum, log_factor));
            }

            Some(LogRewrite {
                rewritten: sum,
                desc: "Auto-expand log product",
            })
        }
        Expr::Div(num, den) => {
            let (num, den) = (*num, *den);
            let log_num = make_log_expr(ctx, base, num);
            let log_den = make_log_expr(ctx, base, den);
            let rewritten = ctx.add(Expr::Sub(log_num, log_den));
            Some(LogRewrite {
                rewritten,
                desc: "Auto-expand log quotient",
            })
        }
        Expr::Pow(pow_base, exp) => {
            let (pow_base, exp) = (*pow_base, *exp);
            let log_base = make_log_expr(ctx, base, pow_base);
            let rewritten = smart_mul(ctx, exp, log_base);
            Some(LogRewrite {
                rewritten,
                desc: "Auto-expand log power",
            })
        }
        _ => None,
    }
}

/// Recursively expand logarithms and collect positivity assumptions as raw expressions.
///
/// Expansion rules:
/// - `log(b, x*y) -> log(b, x) + log(b, y)`
/// - `log(b, x/y) -> log(b, x) - log(b, y)`
///
/// Every expanded multiplicative/division factor is returned in `assumed_positive`.
/// The caller can map those expressions to domain-assumption events in its own layer.
pub fn expand_logs_collect_positive_assumptions(
    ctx: &mut Context,
    expr: ExprId,
) -> ExpandedLogAssumptionPlan {
    fn expand(ctx: &mut Context, expr: ExprId) -> (ExprId, Vec<ExprId>) {
        enum LogKind {
            LogFn(usize, Vec<ExprId>),
            Add(ExprId, ExprId),
            Sub(ExprId, ExprId),
            Mul(ExprId, ExprId),
            Div(ExprId, ExprId),
            Neg(ExprId),
            Pow(ExprId, ExprId),
            Other,
        }

        let kind = match ctx.get(expr) {
            Expr::Function(name, args) => LogKind::LogFn(*name, args.clone()),
            Expr::Add(l, r) => LogKind::Add(*l, *r),
            Expr::Sub(l, r) => LogKind::Sub(*l, *r),
            Expr::Mul(l, r) => LogKind::Mul(*l, *r),
            Expr::Div(l, r) => LogKind::Div(*l, *r),
            Expr::Neg(e) => LogKind::Neg(*e),
            Expr::Pow(b, e) => LogKind::Pow(*b, *e),
            _ => LogKind::Other,
        };
        let mut assumed_positive = Vec::new();

        let result = match kind {
            LogKind::LogFn(name, ref args)
                if matches!(
                    ctx.builtin_of(name),
                    Some(BuiltinFn::Ln) | Some(BuiltinFn::Log)
                ) =>
            {
                // Sentinel reserved by engine/parser bridge for base-10 `log(x)`.
                let sentinel_log10 = ExprId::from_raw(u32::MAX - 1);
                let builtin = ctx.builtin_of(name);
                let (base, arg) = if builtin == Some(BuiltinFn::Log) && args.len() == 1 {
                    (sentinel_log10, args[0])
                } else if let Some((base, arg)) = extract_log_base_argument(ctx, expr) {
                    (base, arg)
                } else {
                    let mut new_args = Vec::with_capacity(args.len());
                    for a in args {
                        let (expanded, sub_assumed_positive) = expand(ctx, *a);
                        new_args.push(expanded);
                        assumed_positive.extend(sub_assumed_positive);
                    }
                    return (ctx.add(Expr::Function(name, new_args)), assumed_positive);
                };

                let (expanded_arg, sub_assumed_positive) = expand(ctx, arg);
                assumed_positive.extend(sub_assumed_positive);
                let (lhs, rhs) = if let Expr::Mul(lhs, rhs) = ctx.get(expanded_arg) {
                    (*lhs, *rhs)
                } else if let Expr::Div(num, den) = ctx.get(expanded_arg) {
                    let (num, den) = (*num, *den);
                    assumed_positive.push(num);
                    assumed_positive.push(den);

                    let log_num = make_log_expr(ctx, base, num);
                    let log_den = make_log_expr(ctx, base, den);
                    let diff = ctx.add(Expr::Sub(log_num, log_den));
                    let (final_result, more_assumed_positive) = expand(ctx, diff);
                    assumed_positive.extend(more_assumed_positive);
                    return (final_result, assumed_positive);
                } else {
                    return (make_log_expr(ctx, base, expanded_arg), assumed_positive);
                };

                assumed_positive.push(lhs);
                assumed_positive.push(rhs);

                let log_lhs = make_log_expr(ctx, base, lhs);
                let log_rhs = make_log_expr(ctx, base, rhs);
                let sum = ctx.add(Expr::Add(log_lhs, log_rhs));
                let (final_result, more_assumed_positive) = expand(ctx, sum);
                assumed_positive.extend(more_assumed_positive);
                return (final_result, assumed_positive);
            }
            LogKind::Add(l, r) => {
                let (el, le) = expand(ctx, l);
                let (er, re) = expand(ctx, r);
                assumed_positive.extend(le);
                assumed_positive.extend(re);
                ctx.add(Expr::Add(el, er))
            }
            LogKind::Sub(l, r) => {
                let (el, le) = expand(ctx, l);
                let (er, re) = expand(ctx, r);
                assumed_positive.extend(le);
                assumed_positive.extend(re);
                ctx.add(Expr::Sub(el, er))
            }
            LogKind::Mul(l, r) => {
                let (el, le) = expand(ctx, l);
                let (er, re) = expand(ctx, r);
                assumed_positive.extend(le);
                assumed_positive.extend(re);
                ctx.add(Expr::Mul(el, er))
            }
            LogKind::Div(l, r) => {
                let (el, le) = expand(ctx, l);
                let (er, re) = expand(ctx, r);
                assumed_positive.extend(le);
                assumed_positive.extend(re);
                ctx.add(Expr::Div(el, er))
            }
            LogKind::Pow(b, e) => {
                let (eb, be) = expand(ctx, b);
                let (ee, exp_e) = expand(ctx, e);
                assumed_positive.extend(be);
                assumed_positive.extend(exp_e);
                ctx.add(Expr::Pow(eb, ee))
            }
            LogKind::Neg(e) => {
                let (ee, sub_e) = expand(ctx, e);
                assumed_positive.extend(sub_e);
                ctx.add(Expr::Neg(ee))
            }
            LogKind::LogFn(name, args) => {
                let mut new_args = Vec::with_capacity(args.len());
                for a in args {
                    let (expanded, sub_assumed_positive) = expand(ctx, a);
                    new_args.push(expanded);
                    assumed_positive.extend(sub_assumed_positive);
                }
                ctx.add(Expr::Function(name, new_args))
            }
            LogKind::Other => expr,
        };

        (result, assumed_positive)
    }

    let (rewritten, assumed_positive) = expand(ctx, expr);
    ExpandedLogAssumptionPlan {
        rewritten,
        assumed_positive,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use cas_parser::parse;

    #[test]
    fn log_detection_handles_nested_product() {
        let mut ctx = Context::new();
        let expr = parse("3*log(x)", &mut ctx).expect("expr");
        assert!(is_log(&ctx, expr));
    }

    #[test]
    fn simplify_exp_log_cancels_matching_base() {
        let mut ctx = Context::new();
        let base = parse("b", &mut ctx).expect("base");
        let exp = parse("log(b,x)", &mut ctx).expect("exp");
        let out = simplify_exp_log(&mut ctx, base, exp);
        let x = parse("x", &mut ctx).expect("x");
        assert_eq!(out, x);
    }

    #[test]
    fn rewrites_split_log_exponents_when_add_contains_log() {
        let mut ctx = Context::new();
        let expr = parse("e^(log(e,x)+k)", &mut ctx).expect("expr");
        let rw = try_rewrite_split_log_exponents_expr(&mut ctx, expr).expect("rewrite");
        assert_eq!(rw.desc, "e^(a+b) -> e^a * e^b (log cancellation)");
    }

    #[test]
    fn does_not_rewrite_split_log_exponents_without_log_term() {
        let mut ctx = Context::new();
        let expr = parse("e^(a+b)", &mut ctx).expect("expr");
        assert!(try_rewrite_split_log_exponents_expr(&mut ctx, expr).is_none());
    }

    #[test]
    fn normalize_to_power_reciprocal_form() {
        let mut ctx = Context::new();
        let expr = parse("1/x", &mut ctx).expect("expr");
        let (_core, exp) = normalize_to_power(&mut ctx, expr);
        assert!(
            matches!(ctx.get(exp), Expr::Number(n) if n.is_integer() && n.to_integer() == (-1).into())
        );
    }

    #[test]
    fn multiplicative_factor_count_and_collect_flatten() {
        let mut ctx = Context::new();
        let expr = parse("a*b*c", &mut ctx).expect("expr");
        assert_eq!(count_mul_factors(&ctx, expr), 3);
        assert_eq!(collect_mul_factors(&ctx, expr).len(), 3);
    }

    #[test]
    fn estimate_log_terms_matches_mul_div_pow_shapes() {
        let mut ctx = Context::new();
        let mul = parse("a*b*c", &mut ctx).expect("mul");
        let div = parse("(a*b)/c", &mut ctx).expect("div");
        let pow = parse("x^4", &mut ctx).expect("pow");

        assert_eq!(estimate_log_terms(&ctx, mul), Some((3, 3, None)));
        assert_eq!(estimate_log_terms(&ctx, div), Some((3, 3, None)));
        assert_eq!(estimate_log_terms(&ctx, pow), Some((1, 1, Some(4))));
    }

    #[test]
    fn eval_log_rational_handles_same_prime_support() {
        let base = num_bigint::BigInt::from(16);
        let val = num_bigint::BigInt::from(8);
        let ratio = eval_log_rational(&base, &val).expect("ratio");
        assert_eq!(ratio, num_rational::BigRational::new(3.into(), 4.into()));
    }

    #[test]
    fn eval_log_rational_rejects_incompatible_support() {
        let base = num_bigint::BigInt::from(6);
        let val = num_bigint::BigInt::from(8);
        assert!(eval_log_rational(&base, &val).is_none());
    }

    #[test]
    fn evaluate_log_rewrite_handles_integer_power_ratio() {
        let mut ctx = Context::new();
        let expr = parse("log(16, 8)", &mut ctx).expect("expr");

        let rw = try_rewrite_evaluate_log_expr(&mut ctx, expr).expect("rewrite");
        assert!(
            matches!(
                ctx.get(rw.rewritten),
                Expr::Number(n)
                    if *n == num_rational::BigRational::new(3.into(), 4.into())
            ),
            "expected numeric 3/4, got {:?}",
            ctx.get(rw.rewritten)
        );
        assert_eq!(rw.desc, "log(16, 8) = 3/4");
        assert_eq!(rw.assume_positive_base, None);
    }

    #[test]
    fn evaluate_log_rewrite_handles_inverse_numeric_exponent() {
        let mut ctx = Context::new();
        let expr = parse("log(x, x^2)", &mut ctx).expect("expr");
        let expected = parse("2", &mut ctx).expect("expected");

        let rw = try_rewrite_evaluate_log_expr(&mut ctx, expr).expect("rewrite");
        assert_eq!(
            cas_ast::ordering::compare_expr(&ctx, rw.rewritten, expected),
            Ordering::Equal
        );
        assert_eq!(rw.assume_positive_base, None);
    }

    #[test]
    fn evaluate_log_rewrite_power_expansion_requests_assumption_subject() {
        let mut ctx = Context::new();
        let expr = parse("log(2, x^3)", &mut ctx).expect("expr");
        let expected = parse("3 * log(2, x)", &mut ctx).expect("expected");
        let x = parse("x", &mut ctx).expect("x");

        let rw = try_rewrite_evaluate_log_expr(&mut ctx, expr).expect("rewrite");
        assert_eq!(
            cas_ast::ordering::compare_expr(&ctx, rw.rewritten, expected),
            Ordering::Equal
        );
        assert_eq!(rw.assume_positive_base, Some(x));
    }

    #[test]
    fn evaluate_log_rewrite_skips_even_power_for_specialized_rule() {
        let mut ctx = Context::new();
        let expr = parse("log(2, x^2)", &mut ctx).expect("expr");
        assert!(try_rewrite_evaluate_log_expr(&mut ctx, expr).is_none());
    }

    #[test]
    fn expand_logs_collect_positive_assumptions_expands_product() {
        let mut ctx = Context::new();
        let expr = parse("log(2, x*y)", &mut ctx).expect("expr");
        let expected = parse("log(2, x) + log(2, y)", &mut ctx).expect("expected");
        let x = parse("x", &mut ctx).expect("x");
        let y = parse("y", &mut ctx).expect("y");

        let plan = expand_logs_collect_positive_assumptions(&mut ctx, expr);
        assert_eq!(
            cas_ast::ordering::compare_expr(&ctx, plan.rewritten, expected),
            Ordering::Equal
        );
        assert_eq!(plan.assumed_positive.len(), 2);
        assert!(plan.assumed_positive.contains(&x));
        assert!(plan.assumed_positive.contains(&y));
    }

    #[test]
    fn expand_logs_collect_positive_assumptions_expands_quotient() {
        let mut ctx = Context::new();
        let expr = parse("log(2, x/y)", &mut ctx).expect("expr");
        let expected = parse("log(2, x) - log(2, y)", &mut ctx).expect("expected");
        let x = parse("x", &mut ctx).expect("x");
        let y = parse("y", &mut ctx).expect("y");

        let plan = expand_logs_collect_positive_assumptions(&mut ctx, expr);
        assert_eq!(
            cas_ast::ordering::compare_expr(&ctx, plan.rewritten, expected),
            Ordering::Equal
        );
        assert_eq!(plan.assumed_positive.len(), 2);
        assert_eq!(plan.assumed_positive[0], x);
        assert_eq!(plan.assumed_positive[1], y);
    }

    #[test]
    fn rewrite_log_mul_div_expansion_rewrites_product() {
        let mut ctx = Context::new();
        let expr = parse("log(2, x*y)", &mut ctx).expect("expr");
        let expected = parse("log(2, x) + log(2, y)", &mut ctx).expect("expected");
        let x = parse("x", &mut ctx).expect("x");
        let y = parse("y", &mut ctx).expect("y");

        let rw = try_rewrite_log_mul_div_expansion_expr(&mut ctx, expr).expect("rewrite");
        assert_eq!(
            cas_ast::ordering::compare_expr(&ctx, rw.rewritten, expected),
            Ordering::Equal
        );
        assert_eq!(rw.positive_lhs, x);
        assert_eq!(rw.positive_rhs, y);
        assert_eq!(rw.desc, "log(b, x*y) = log(b, x) + log(b, y)");
    }

    #[test]
    fn rewrite_log_mul_div_expansion_rewrites_quotient() {
        let mut ctx = Context::new();
        let expr = parse("log(2, x/y)", &mut ctx).expect("expr");
        let expected = parse("log(2, x) - log(2, y)", &mut ctx).expect("expected");
        let x = parse("x", &mut ctx).expect("x");
        let y = parse("y", &mut ctx).expect("y");

        let rw = try_rewrite_log_mul_div_expansion_expr(&mut ctx, expr).expect("rewrite");
        assert_eq!(
            cas_ast::ordering::compare_expr(&ctx, rw.rewritten, expected),
            Ordering::Equal
        );
        assert_eq!(rw.positive_lhs, x);
        assert_eq!(rw.positive_rhs, y);
        assert_eq!(rw.desc, "log(b, x/y) = log(b, x) - log(b, y)");
    }

    #[test]
    fn rewrite_log_mul_div_expansion_rejects_non_mul_div_arg() {
        let mut ctx = Context::new();
        let expr = parse("log(2, x+1)", &mut ctx).expect("expr");
        assert!(try_rewrite_log_mul_div_expansion_expr(&mut ctx, expr).is_none());
    }

    #[test]
    fn rewrite_log_perfect_square_expr_rewrites_even_power() {
        let mut ctx = Context::new();
        let expr = parse("ln(x^4)", &mut ctx).expect("expr");
        let expected = parse("2 * ln(abs(x^2))", &mut ctx).expect("expected");

        let rw = try_rewrite_log_perfect_square_expr(&mut ctx, expr).expect("rewrite");
        assert_eq!(
            cas_ast::ordering::compare_expr(&ctx, rw.rewritten, expected),
            Ordering::Equal
        );
    }

    #[test]
    fn rewrite_log_perfect_square_expr_rewrites_symbolic_trinomial() {
        let mut ctx = Context::new();
        let expr = parse("ln(x^2 + 2*x*y + y^2)", &mut ctx).expect("expr");
        let expected = parse("2 * ln(abs(x + y))", &mut ctx).expect("expected");

        let rw = try_rewrite_log_perfect_square_expr(&mut ctx, expr).expect("rewrite");
        assert_eq!(
            cas_ast::ordering::compare_expr(&ctx, rw.rewritten, expected),
            Ordering::Equal
        );
    }

    #[test]
    fn plan_log_even_power_abs_expr_accepts_even_power() {
        let mut ctx = Context::new();
        let expr = parse("log(2, x^4)", &mut ctx).expect("expr");
        let expected_with_abs = parse("4 * log(2, abs(x))", &mut ctx).expect("with_abs");
        let expected_without_abs = parse("4 * log(2, x)", &mut ctx).expect("without_abs");
        let x = parse("x", &mut ctx).expect("x");
        let abs_x = parse("abs(x)", &mut ctx).expect("abs_x");

        let plan = try_plan_log_even_power_abs_expr(&mut ctx, expr).expect("plan");
        assert_eq!(plan.inner_base, x);
        assert_eq!(plan.abs_inner_base, abs_x);
        assert_eq!(
            cas_ast::ordering::compare_expr(&ctx, plan.with_abs_rewrite, expected_with_abs),
            Ordering::Equal
        );
        assert_eq!(
            cas_ast::ordering::compare_expr(&ctx, plan.without_abs_rewrite, expected_without_abs),
            Ordering::Equal
        );
    }

    #[test]
    fn plan_log_even_power_abs_expr_rejects_inverse_composition() {
        let mut ctx = Context::new();
        let expr = parse("log(x, x^4)", &mut ctx).expect("expr");
        assert!(try_plan_log_even_power_abs_expr(&mut ctx, expr).is_none());
    }

    #[test]
    fn plan_log_even_power_abs_expr_rejects_ln_exp_power() {
        let mut ctx = Context::new();
        let x = parse("x", &mut ctx).expect("x");
        let exp_x = ctx.call_builtin(BuiltinFn::Exp, vec![x]);
        let four = ctx.num(4);
        let arg = ctx.add(Expr::Pow(exp_x, four));
        let expr = ctx.call_builtin(BuiltinFn::Ln, vec![arg]);
        assert!(try_plan_log_even_power_abs_expr(&mut ctx, expr).is_none());
    }

    #[test]
    fn rewrite_log_abs_power_expr_rewrites_positive_integer_power() {
        let mut ctx = Context::new();
        let expr = parse("log(2, abs(x)^3)", &mut ctx).expect("expr");
        let expected = parse("3 * log(2, abs(x))", &mut ctx).expect("expected");
        let x = parse("x", &mut ctx).expect("x");

        let rw = try_rewrite_log_abs_power_expr(&mut ctx, expr).expect("rewrite");
        assert_eq!(
            cas_ast::ordering::compare_expr(&ctx, rw.rewritten, expected),
            Ordering::Equal
        );
        assert_eq!(rw.inner_subject, x);
        assert_eq!(rw.desc, "ln(|u|^n) = n·ln(|u|)");
    }

    #[test]
    fn rewrite_log_abs_power_expr_rejects_non_abs_base() {
        let mut ctx = Context::new();
        let expr = parse("log(2, x^3)", &mut ctx).expect("expr");
        assert!(try_rewrite_log_abs_power_expr(&mut ctx, expr).is_none());
    }

    #[test]
    fn rewrite_log_abs_power_expr_rejects_non_positive_integer_exponent() {
        let mut ctx = Context::new();
        let zero = parse("log(2, abs(x)^0)", &mut ctx).expect("zero");
        let frac = parse("log(2, abs(x)^(1/2))", &mut ctx).expect("frac");
        assert!(try_rewrite_log_abs_power_expr(&mut ctx, zero).is_none());
        assert!(try_rewrite_log_abs_power_expr(&mut ctx, frac).is_none());
    }

    #[test]
    fn make_log_expr_uses_ln_for_e_base() {
        let mut ctx = Context::new();
        let e = ctx.add(Expr::Constant(cas_ast::Constant::E));
        let x = ctx.var("x");
        let out = make_log_expr(&mut ctx, e, x);
        let rendered = format!(
            "{}",
            cas_formatter::DisplayExpr {
                context: &ctx,
                id: out
            }
        );
        assert_eq!(rendered, "ln(x)");
    }

    #[test]
    fn rewrites_ln_e_product_and_division_patterns() {
        let mut ctx = Context::new();

        let prod = parse("ln(e*x)", &mut ctx).expect("prod");
        let div1 = parse("ln(x/e)", &mut ctx).expect("div1");
        let div2 = parse("ln(e/x)", &mut ctx).expect("div2");

        assert_eq!(
            try_rewrite_ln_e_product_expr(&mut ctx, prod)
                .expect("prod rewrite")
                .rewritten,
            parse("1 + ln(x)", &mut ctx).expect("prod expected")
        );
        assert_eq!(
            try_rewrite_ln_e_div_expr(&mut ctx, div1)
                .expect("div1 rewrite")
                .kind,
            LnEDivRewriteKind::XOverE
        );
        assert_eq!(
            try_rewrite_ln_e_div_expr(&mut ctx, div2)
                .expect("div2 rewrite")
                .kind,
            LnEDivRewriteKind::EOverX
        );
    }

    #[test]
    fn log_base_and_expr_matching_respects_ln_sentinel() {
        let mut ctx = Context::new();
        let e = ctx.add(Expr::Constant(cas_ast::Constant::E));
        let x = ctx.var("x");
        let y = ctx.var("y");
        let sentinel = ln_base_sentinel();

        assert!(exprs_match_for_logs(&ctx, sentinel, e));
        assert!(bases_equal_for_logs(&ctx, sentinel, e));
        assert!(!bases_equal_for_logs(&ctx, x, y));
    }

    #[test]
    fn extract_log_parts_handles_ln_and_log() {
        let mut ctx = Context::new();
        let x = ctx.var("x");
        let b = ctx.var("b");
        let ln_x = ctx.call_builtin(BuiltinFn::Ln, vec![x]);
        let log_bx = ctx.call_builtin(BuiltinFn::Log, vec![b, x]);

        let (ln_base, ln_arg) = try_extract_log_parts(&ctx, ln_x).expect("ln parts");
        assert_eq!(ln_base, ln_base_sentinel());
        assert_eq!(ln_arg, x);

        let (log_base, log_arg) = try_extract_log_parts(&ctx, log_bx).expect("log parts");
        assert_eq!(log_base, b);
        assert_eq!(log_arg, x);
    }

    #[test]
    fn contracts_log_add_and_sub_pairwise() {
        let mut ctx = Context::new();
        let x = ctx.var("x");
        let y = ctx.var("y");
        let b = ctx.var("b");
        let log_bx = ctx.call_builtin(BuiltinFn::Log, vec![b, x]);
        let log_by = ctx.call_builtin(BuiltinFn::Log, vec![b, y]);

        let add_expr = ctx.add(Expr::Add(log_bx, log_by));
        let sub_expr = ctx.add(Expr::Sub(log_bx, log_by));

        let add_rw = try_rewrite_log_contraction_expr(&mut ctx, add_expr).expect("add rw");
        let sub_rw = try_rewrite_log_contraction_expr(&mut ctx, sub_expr).expect("sub rw");

        assert_eq!(add_rw.kind, LogContractionRewriteKind::Add);
        assert_eq!(sub_rw.kind, LogContractionRewriteKind::Sub);
    }

    #[test]
    fn contracts_log_chain_product_pair() {
        let mut ctx = Context::new();
        let expr = parse("log(b,a)*log(a,c)", &mut ctx).expect("expr");
        let expected = parse("log(b,c)", &mut ctx).expect("expected");

        let rw = try_rewrite_log_chain_product_expr(&mut ctx, expr).expect("chain rw");
        assert_eq!(rw.kind, LogChainProductRewriteKind::Telescoping);
        assert_eq!(
            cas_ast::ordering::compare_expr(&ctx, rw.rewritten, expected),
            Ordering::Equal
        );
    }

    #[test]
    fn contracts_log_chain_product_with_remaining_factor() {
        let mut ctx = Context::new();
        let expr = parse("k*log(b,a)*log(a,c)", &mut ctx).expect("expr");
        let k = parse("k", &mut ctx).expect("k");
        let expected_log = parse("log(b,c)", &mut ctx).expect("expected_log");

        let rw = try_rewrite_log_chain_product_expr(&mut ctx, expr).expect("chain rw");
        let factors = MulView::from_expr(&ctx, rw.rewritten).factors;
        assert_eq!(factors.len(), 2);
        assert!(factors.contains(&k));
        assert!(factors.contains(&expected_log));
    }

    #[test]
    fn does_not_contract_non_telescope_log_chain() {
        let mut ctx = Context::new();
        let expr = parse("log(b,a)*log(d,c)", &mut ctx).expect("expr");
        assert!(try_rewrite_log_chain_product_expr(&mut ctx, expr).is_none());
    }

    #[test]
    fn rewrites_log_inverse_power_div_form() {
        let mut ctx = Context::new();
        let expr = parse("x^(2/log(3,x))", &mut ctx).expect("expr");
        let expected = parse("3^2", &mut ctx).expect("expected");

        let rw = try_rewrite_log_inverse_power_expr(&mut ctx, expr).expect("rewrite");
        assert_eq!(
            cas_ast::ordering::compare_expr(&ctx, rw.rewritten, expected),
            Ordering::Equal
        );
    }

    #[test]
    fn rewrites_log_inverse_power_ln_form() {
        let mut ctx = Context::new();
        let expr = parse("x^(1/ln(x))", &mut ctx).expect("expr");
        let rw = try_rewrite_log_inverse_power_expr(&mut ctx, expr).expect("rewrite");
        match ctx.get(rw.rewritten) {
            Expr::Constant(Constant::E) => {}
            Expr::Pow(base, exp) => {
                assert!(is_e_constant_expr(&ctx, *base));
                assert!(matches!(ctx.get(*exp), Expr::Number(n) if n.is_one()));
            }
            other => panic!("expected e or e^1, got {:?}", other),
        }
    }

    #[test]
    fn does_not_rewrite_log_inverse_power_when_log_arg_differs() {
        let mut ctx = Context::new();
        let expr = parse("x^(2/log(3,y))", &mut ctx).expect("expr");
        assert!(try_rewrite_log_inverse_power_expr(&mut ctx, expr).is_none());
    }

    #[test]
    fn rewrites_exponential_log_inverse_direct_and_mul_forms() {
        let mut ctx = Context::new();
        let direct = parse("b^log(b,x)", &mut ctx).expect("direct");
        let mul = parse("b^(c*log(b,x))", &mut ctx).expect("mul");
        let x = parse("x", &mut ctx).expect("x");
        let x_pow_c = parse("x^c", &mut ctx).expect("x_pow_c");

        let rw_direct = try_rewrite_exponential_log_inverse_expr(&mut ctx, direct).expect("direct");
        let rw_mul = try_rewrite_exponential_log_inverse_expr(&mut ctx, mul).expect("mul");

        assert_eq!(
            cas_ast::ordering::compare_expr(&ctx, rw_direct.rewritten, x),
            Ordering::Equal
        );
        assert_eq!(
            cas_ast::ordering::compare_expr(&ctx, rw_mul.rewritten, x_pow_c),
            Ordering::Equal
        );
        assert_eq!(rw_direct.positive_subject, x);
    }

    #[test]
    fn does_not_rewrite_exponential_log_inverse_when_base_mismatch() {
        let mut ctx = Context::new();
        let expr = parse("b^log(a,x)", &mut ctx).expect("expr");
        assert!(try_rewrite_exponential_log_inverse_expr(&mut ctx, expr).is_none());
    }

    #[test]
    fn matches_log_exp_inverse_numeric_and_symbolic() {
        let mut ctx = Context::new();
        let numeric = parse("log(b, b^2)", &mut ctx).expect("numeric");
        let symbolic = parse("log(b, b^x)", &mut ctx).expect("symbolic");

        let numeric_match = try_match_log_exp_inverse_expr(&mut ctx, numeric).expect("numeric");
        let symbolic_match = try_match_log_exp_inverse_expr(&mut ctx, symbolic).expect("symbolic");

        assert!(matches!(numeric_match, LogExpInverseMatch::Numeric { .. }));
        assert!(matches!(
            symbolic_match,
            LogExpInverseMatch::Symbolic { .. }
        ));
    }

    #[test]
    fn rewrites_log_power_base_numeric_ratio() {
        let mut ctx = Context::new();
        let expr = parse("log(x^2, x^6)", &mut ctx).expect("expr");
        let expected = parse("3", &mut ctx).expect("expected");

        let rw = try_rewrite_log_power_base_numeric_expr(&mut ctx, expr).expect("rewrite");
        assert_eq!(
            cas_ast::ordering::compare_expr(&ctx, rw.rewritten, expected),
            Ordering::Equal
        );
        assert_eq!(rw.desc, "log(a^2, a^6) = 6/2 = 3");
    }

    #[test]
    fn does_not_rewrite_log_power_base_when_base_exp_is_one() {
        let mut ctx = Context::new();
        let expr = parse("log(x, x^2)", &mut ctx).expect("expr");
        assert!(try_rewrite_log_power_base_numeric_expr(&mut ctx, expr).is_none());
    }

    #[test]
    fn auto_expand_positivity_plan_strict_blocks_unproven() {
        let mut ctx = Context::new();
        let expr = parse("x*y", &mut ctx).expect("expr");
        let x = parse("x", &mut ctx).expect("x");
        let y = parse("y", &mut ctx).expect("y");

        let plan = plan_log_auto_expand_positivity(
            &ctx,
            expr,
            LogAutoExpandMode::Strict,
            |factor| factor == x,
            |_| false,
        );

        assert_eq!(plan, LogAutoExpandPositivityPlan::Blocked { factor: y });
    }

    #[test]
    fn auto_expand_positivity_plan_generic_accepts_implied() {
        let mut ctx = Context::new();
        let expr = parse("x*y", &mut ctx).expect("expr");

        let plan = plan_log_auto_expand_positivity(
            &ctx,
            expr,
            LogAutoExpandMode::Generic,
            |_| false,
            |_| true,
        );

        assert_eq!(plan, LogAutoExpandPositivityPlan::AllowNoAssumptions);
    }

    #[test]
    fn auto_expand_positivity_plan_assume_collects_unproven() {
        let mut ctx = Context::new();
        let expr = parse("x*y", &mut ctx).expect("expr");
        let x = parse("x", &mut ctx).expect("x");
        let y = parse("y", &mut ctx).expect("y");

        let plan = plan_log_auto_expand_positivity(
            &ctx,
            expr,
            LogAutoExpandMode::Assume,
            |factor| factor == x,
            |_| false,
        );

        assert_eq!(
            plan,
            LogAutoExpandPositivityPlan::AllowWithAssumptions(vec![y])
        );
    }

    #[test]
    fn mode_from_flags_prioritizes_assume_then_strict() {
        assert_eq!(
            log_auto_expand_mode_from_flags(true, true),
            LogAutoExpandMode::Assume
        );
        assert_eq!(
            log_auto_expand_mode_from_flags(false, true),
            LogAutoExpandMode::Strict
        );
        assert_eq!(
            log_auto_expand_mode_from_flags(false, false),
            LogAutoExpandMode::Generic
        );

        assert_eq!(
            log_exp_inverse_policy_mode_from_flags(true, true),
            LogExpInversePolicyMode::Assume
        );
        assert_eq!(
            log_exp_inverse_policy_mode_from_flags(false, true),
            LogExpInversePolicyMode::Strict
        );
        assert_eq!(
            log_exp_inverse_policy_mode_from_flags(false, false),
            LogExpInversePolicyMode::Generic
        );
    }

    #[test]
    fn auto_expand_mode_helpers_only_enable_generic_paths() {
        assert!(log_auto_expand_needs_implicit_domain(
            LogAutoExpandMode::Generic
        ));
        assert!(!log_auto_expand_needs_implicit_domain(
            LogAutoExpandMode::Strict
        ));
        assert!(log_auto_expand_emits_blocked_hint(
            LogAutoExpandMode::Generic
        ));
        assert!(!log_auto_expand_emits_blocked_hint(
            LogAutoExpandMode::Assume
        ));
    }

    #[test]
    fn log_exp_inverse_policy_blocks_in_complex() {
        let plan = plan_log_exp_inverse_symbolic_policy(
            LogExpInversePolicyMode::Strict,
            true,
            false,
            true,
            false,
        );
        assert_eq!(plan, LogExpInversePolicyPlan::Block);
    }

    #[test]
    fn log_exp_inverse_policy_requires_assume_for_unproven_non_e_base() {
        let strict = plan_log_exp_inverse_symbolic_policy(
            LogExpInversePolicyMode::Strict,
            false,
            false,
            false,
            false,
        );
        let assume = plan_log_exp_inverse_symbolic_policy(
            LogExpInversePolicyMode::Assume,
            false,
            false,
            false,
            false,
        );
        assert_eq!(strict, LogExpInversePolicyPlan::Block);
        assert_eq!(
            assume,
            LogExpInversePolicyPlan::Rewrite {
                assume_positive_base: true
            }
        );
    }

    #[test]
    fn log_exp_inverse_policy_blocks_base_one_and_allows_e_base() {
        let base_one = plan_log_exp_inverse_symbolic_policy(
            LogExpInversePolicyMode::Generic,
            false,
            false,
            true,
            true,
        );
        let e_base = plan_log_exp_inverse_symbolic_policy(
            LogExpInversePolicyMode::Strict,
            false,
            true,
            false,
            false,
        );
        assert_eq!(base_one, LogExpInversePolicyPlan::Block);
        assert_eq!(
            e_base,
            LogExpInversePolicyPlan::Rewrite {
                assume_positive_base: false
            }
        );
    }

    #[test]
    fn exponential_log_inverse_policy_strict_vs_generic() {
        let strict_unproven =
            plan_exponential_log_inverse_policy(LogExpInversePolicyMode::Strict, false);
        let generic_unproven =
            plan_exponential_log_inverse_policy(LogExpInversePolicyMode::Generic, false);
        let strict_proven =
            plan_exponential_log_inverse_policy(LogExpInversePolicyMode::Strict, true);

        assert_eq!(strict_unproven, ExponentialLogInversePolicyPlan::Block);
        assert_eq!(
            generic_unproven,
            ExponentialLogInversePolicyPlan::Rewrite {
                require_positive_subject: true
            }
        );
        assert_eq!(
            strict_proven,
            ExponentialLogInversePolicyPlan::Rewrite {
                require_positive_subject: false
            }
        );
    }

    #[test]
    fn log_power_base_policy_blocks_complex_and_strict_invalid() {
        let complex =
            plan_log_power_base_numeric_policy(LogExpInversePolicyMode::Generic, true, true, false);
        let strict_unproven = plan_log_power_base_numeric_policy(
            LogExpInversePolicyMode::Strict,
            false,
            false,
            false,
        );
        let strict_base_one =
            plan_log_power_base_numeric_policy(LogExpInversePolicyMode::Strict, false, true, true);
        assert_eq!(complex, LogPowerBasePolicyPlan::Block);
        assert_eq!(strict_unproven, LogPowerBasePolicyPlan::Block);
        assert_eq!(strict_base_one, LogPowerBasePolicyPlan::Block);
    }

    #[test]
    fn log_power_base_policy_rewrite_flags_match_mode() {
        let generic = plan_log_power_base_numeric_policy(
            LogExpInversePolicyMode::Generic,
            false,
            false,
            false,
        );
        let assume_unproven = plan_log_power_base_numeric_policy(
            LogExpInversePolicyMode::Assume,
            false,
            false,
            false,
        );
        let assume_proven =
            plan_log_power_base_numeric_policy(LogExpInversePolicyMode::Assume, false, true, false);

        assert_eq!(
            generic,
            LogPowerBasePolicyPlan::Rewrite {
                require_positive_base: false,
                require_nonzero_base_minus_one: true
            }
        );
        assert_eq!(
            assume_unproven,
            LogPowerBasePolicyPlan::Rewrite {
                require_positive_base: true,
                require_nonzero_base_minus_one: true
            }
        );
        assert_eq!(
            assume_proven,
            LogPowerBasePolicyPlan::Rewrite {
                require_positive_base: false,
                require_nonzero_base_minus_one: true
            }
        );
    }

    #[test]
    fn log_even_power_policy_blocks_without_positive_or_requires() {
        let strict_block =
            plan_log_even_power_policy(LogExpInversePolicyMode::Strict, false, false, false);
        let generic_block =
            plan_log_even_power_policy(LogExpInversePolicyMode::Generic, false, false, false);
        assert_eq!(strict_block, LogEvenPowerPolicyPlan::Block);
        assert_eq!(generic_block, LogEvenPowerPolicyPlan::Block);
    }

    #[test]
    fn log_even_power_policy_chains_when_proven_or_requires() {
        let strict_proven =
            plan_log_even_power_policy(LogExpInversePolicyMode::Strict, true, false, false);
        let strict_requires =
            plan_log_even_power_policy(LogExpInversePolicyMode::Strict, false, true, true);
        assert_eq!(
            strict_proven,
            LogEvenPowerPolicyPlan::RewriteWithChain {
                chain_desc: "|x| = x for x > 0",
                assume_positive_subject: false
            }
        );
        assert_eq!(
            strict_requires,
            LogEvenPowerPolicyPlan::RewriteWithChain {
                chain_desc: "|x| = x for x > 0",
                assume_positive_subject: false
            }
        );
    }

    #[test]
    fn log_even_power_policy_assume_mode_matches_existing_behavior() {
        let assume_unknown =
            plan_log_even_power_policy(LogExpInversePolicyMode::Assume, false, false, false);
        let assume_disproven =
            plan_log_even_power_policy(LogExpInversePolicyMode::Assume, false, true, false);
        assert_eq!(
            assume_unknown,
            LogEvenPowerPolicyPlan::RewriteWithChain {
                chain_desc: "|x| = x (assuming x > 0)",
                assume_positive_subject: true
            }
        );
        assert_eq!(
            assume_disproven,
            LogEvenPowerPolicyPlan::RewriteWithAbsAssume {
                assume_positive_subject: true
            }
        );
    }

    #[test]
    fn log_even_power_requires_lookup_gate_matches_policy_sensitivity() {
        assert!(log_even_power_needs_requires_lookup(
            LogExpInversePolicyMode::Strict,
            false,
            false
        ));
        assert!(!log_even_power_needs_requires_lookup(
            LogExpInversePolicyMode::Strict,
            true,
            false
        ));

        assert!(log_even_power_needs_requires_lookup(
            LogExpInversePolicyMode::Assume,
            false,
            false
        ));
        assert!(!log_even_power_needs_requires_lookup(
            LogExpInversePolicyMode::Assume,
            false,
            true
        ));
    }

    #[test]
    fn auto_expand_log_product_rewrite() {
        let mut ctx = Context::new();
        let expr = parse("log(b, x*y)", &mut ctx).expect("expr");
        let (_, arg) = extract_log_base_argument_view(&ctx, expr).expect("parts");
        let rw = try_expand_log_auto_rule_expr(&mut ctx, expr, arg).expect("rewrite");
        assert_eq!(rw.desc, "Auto-expand log product");
    }

    #[test]
    fn auto_expand_log_quotient_rewrite() {
        let mut ctx = Context::new();
        let expr = parse("ln(x/y)", &mut ctx).expect("expr");
        let (_, arg) = extract_log_base_argument_view(&ctx, expr).expect("parts");
        let rw = try_expand_log_auto_rule_expr(&mut ctx, expr, arg).expect("rewrite");
        assert_eq!(rw.desc, "Auto-expand log quotient");
    }

    #[test]
    fn auto_expand_log_power_rewrite() {
        let mut ctx = Context::new();
        let expr = parse("log(b, x^n)", &mut ctx).expect("expr");
        let (_, arg) = extract_log_base_argument_view(&ctx, expr).expect("parts");
        let rw = try_expand_log_auto_rule_expr(&mut ctx, expr, arg).expect("rewrite");
        assert_eq!(rw.desc, "Auto-expand log power");
    }
}
