use crate::Step;
use cas_ast::{Context, ExprId};
use cas_math::expand_eager::{
    eager_eval_expand_calls_with, DEFAULT_EAGER_EXPAND_MATERIALIZE_LIMIT,
    DEFAULT_EAGER_EXPAND_MODP_THRESHOLD,
};
use cas_math::expand_ops;
/// Threshold for using fast mod-p expansion in eager eval.
/// Above this many estimated terms, use poly_ref instead of AST.
pub const EAGER_EXPAND_MODP_THRESHOLD: u64 = DEFAULT_EAGER_EXPAND_MODP_THRESHOLD;
/// Threshold for returning poly_ref instead of materializing AST.
/// Below this, we materialize the full AST for display.
pub const EXPAND_MATERIALIZE_LIMIT: usize = DEFAULT_EAGER_EXPAND_MATERIALIZE_LIMIT;

/// Eager evaluation pass for expand() calls.
///
/// This runs BEFORE the simplification pipeline to avoid budget exhaustion
/// from processing large polynomial children.
///
/// Strategy:
/// - For expand(arg) where estimated terms > threshold: use fast mod-p expansion
/// - If terms > EXPAND_MATERIALIZE_LIMIT: return poly_ref (opaque)
/// - Otherwise: materialize AST wrapped in __hold
pub fn eager_eval_expand_calls(
    ctx: &mut Context,
    expr: ExprId,
    collect_steps: bool,
) -> (ExprId, Vec<Step>) {
    eager_eval_expand_calls_with(
        ctx,
        expr,
        collect_steps,
        EAGER_EXPAND_MODP_THRESHOLD,
        EXPAND_MATERIALIZE_LIMIT,
        |core_ctx, est, before, after| {
            Step::new(
                &format!("Eager expand (mod-p, {} terms)", est),
                "Polynomial Expansion",
                before,
                after,
                Vec::new(),
                Some(core_ctx),
            )
        },
    )
}

/// Expand with budget tracking, returning PassStats for unified budget charging.
///
/// Tracks `nodes_delta` and estimates `terms_materialized` based on the expansion.
pub fn expand_with_stats(ctx: &mut Context, expr: ExprId) -> (ExprId, crate::budget::PassStats) {
    let nodes_snap = ctx.stats().nodes_created;

    // Estimate terms before expansion (if Pow(Add, n))
    let estimated_terms = estimate_expand_terms(ctx, expr).unwrap_or(0);

    let result = expand(ctx, expr);

    let nodes_delta = ctx.stats().nodes_created.saturating_sub(nodes_snap);

    let stats = crate::budget::PassStats {
        op: crate::budget::Operation::Expand,
        rewrite_count: 0, // Expand doesn't use rewrites
        nodes_delta,
        terms_materialized: estimated_terms,
        poly_ops: 0,
        stop_reason: None, // Budget checking happens via MultinomialExpandBudget
    };

    (result, stats)
}

/// Estimate number of terms that will be generated by expansion.
/// Returns None if not an expandable pattern or unable to estimate.
pub fn estimate_expand_terms(ctx: &Context, expr: ExprId) -> Option<u64> {
    cas_math::expand_estimate::estimate_expand_terms(ctx, expr)
}

/// Expands an expression.
/// This is the main entry point for expansion.
/// It recursively expands children and then applies specific expansion rules.
pub fn expand(ctx: &mut Context, expr: ExprId) -> ExprId {
    expand_ops::expand(ctx, expr)
}

/// Expands multiplication: distributes over addition/subtraction.
/// a * (b + c) -> a*b + a*c
pub fn expand_mul(ctx: &mut Context, l: ExprId, r: ExprId) -> ExprId {
    expand_ops::expand_mul(ctx, l, r)
}

/// Expands division: distributes over addition/subtraction in numerator.
/// (a + b) / c -> a/c + b/c
pub fn expand_div(ctx: &mut Context, num: ExprId, den: ExprId) -> ExprId {
    expand_ops::expand_div(ctx, num, den)
}

/// Evaluate one `expand(...)` call in an isolated, steps-off simplifier context.
///
/// Used by rule-level wrappers that need expansion behavior without polluting
/// the caller's simplifier state.
pub(crate) fn eval_expand_off(core_ctx: &mut Context, expand_call: ExprId) -> ExprId {
    use crate::options::StepsMode;
    use crate::phase::ExpandPolicy;

    let opts = crate::options::EvalOptions {
        steps_mode: StepsMode::Off,
        shared: crate::phase::SharedSemanticConfig {
            expand_policy: ExpandPolicy::Off,
            ..Default::default()
        },
        ..Default::default()
    };
    let mut simplifier = crate::engine::Simplifier::with_profile(&opts);
    simplifier.set_steps_mode(StepsMode::Off);

    std::mem::swap(&mut simplifier.context, core_ctx);
    let (result, _) = simplifier.expand(expand_call);
    std::mem::swap(&mut simplifier.context, core_ctx);
    result
}

/// Expands power: (a + b)^n
/// Note: Fast multinomial expansion is handled in expand() BEFORE children are processed.
pub fn expand_pow(ctx: &mut Context, base: ExprId, exp: ExprId) -> ExprId {
    expand_ops::expand_pow(ctx, base, exp)
}
