use crate::Step;
use cas_ast::{Context, ExprId};
use cas_math::expand_eager::eager_eval_expand_calls_with;
use cas_math::expand_ops;
/// Threshold for using fast mod-p expansion in eager eval.
/// Above this many estimated terms, use poly_ref instead of AST.
pub const EAGER_EXPAND_MODP_THRESHOLD: u64 = 500;
/// Threshold for returning poly_ref instead of materializing AST.
/// Below this, we materialize the full AST for display.
pub const EXPAND_MATERIALIZE_LIMIT: usize = 1_000;

/// Eager evaluation pass for expand() calls.
///
/// This runs BEFORE the simplification pipeline to avoid budget exhaustion
/// from processing large polynomial children.
///
/// Strategy:
/// - For expand(arg) where estimated terms > threshold: use fast mod-p expansion
/// - If terms > EXPAND_MATERIALIZE_LIMIT: return poly_ref (opaque)
/// - Otherwise: materialize AST wrapped in __hold
pub fn eager_eval_expand_calls(
    ctx: &mut Context,
    expr: ExprId,
    collect_steps: bool,
) -> (ExprId, Vec<Step>) {
    eager_eval_expand_calls_with(
        ctx,
        expr,
        collect_steps,
        EAGER_EXPAND_MODP_THRESHOLD,
        EXPAND_MATERIALIZE_LIMIT,
        |core_ctx, est, before, after| {
            Step::new(
                &format!("Eager expand (mod-p, {} terms)", est),
                "Polynomial Expansion",
                before,
                after,
                Vec::new(),
                Some(core_ctx),
            )
        },
    )
}

/// Expand with budget tracking, returning PassStats for unified budget charging.
///
/// Tracks `nodes_delta` and estimates `terms_materialized` based on the expansion.
pub fn expand_with_stats(ctx: &mut Context, expr: ExprId) -> (ExprId, crate::budget::PassStats) {
    let nodes_snap = ctx.stats().nodes_created;

    // Estimate terms before expansion (if Pow(Add, n))
    let estimated_terms = estimate_expand_terms(ctx, expr).unwrap_or(0);

    let result = expand(ctx, expr);

    let nodes_delta = ctx.stats().nodes_created.saturating_sub(nodes_snap);

    let stats = crate::budget::PassStats {
        op: crate::budget::Operation::Expand,
        rewrite_count: 0, // Expand doesn't use rewrites
        nodes_delta,
        terms_materialized: estimated_terms,
        poly_ops: 0,
        stop_reason: None, // Budget checking happens via MultinomialExpandBudget
    };

    (result, stats)
}

/// Estimate number of terms that will be generated by expansion.
/// Returns None if not an expandable pattern or unable to estimate.
pub fn estimate_expand_terms(ctx: &Context, expr: ExprId) -> Option<u64> {
    cas_math::expand_estimate::estimate_expand_terms(ctx, expr)
}

/// Expands an expression.
/// This is the main entry point for expansion.
/// It recursively expands children and then applies specific expansion rules.
pub fn expand(ctx: &mut Context, expr: ExprId) -> ExprId {
    expand_ops::expand(ctx, expr)
}

/// Expands multiplication: distributes over addition/subtraction.
/// a * (b + c) -> a*b + a*c
pub fn expand_mul(ctx: &mut Context, l: ExprId, r: ExprId) -> ExprId {
    expand_ops::expand_mul(ctx, l, r)
}

/// Expands division: distributes over addition/subtraction in numerator.
/// (a + b) / c -> a/c + b/c
pub fn expand_div(ctx: &mut Context, num: ExprId, den: ExprId) -> ExprId {
    expand_ops::expand_div(ctx, num, den)
}

/// Expands power: (a + b)^n
/// Note: Fast multinomial expansion is handled in expand() BEFORE children are processed.
pub fn expand_pow(ctx: &mut Context, base: ExprId, exp: ExprId) -> ExprId {
    expand_ops::expand_pow(ctx, base, exp)
}

#[cfg(test)]
mod tests {
    use super::*;
    use cas_formatter::DisplayExpr;
    use cas_parser::parse;

    fn s(ctx: &Context, id: ExprId) -> String {
        format!("{}", DisplayExpr { context: ctx, id })
    }

    #[test]
    fn test_expand_mul_distribute() {
        let mut ctx = Context::new();
        let expr = parse("2 * (x + 3)", &mut ctx).unwrap();
        let res = expand(&mut ctx, expr);
        // 2*x + 2*3. Note: 2*3 is not simplified here, expand is structural.
        // But wait, expand calls expand_mul which constructs Mul.
        // If we want simplification, we need a simplifier or builder that simplifies.
        // The current `ctx.add` just adds nodes.
        // So we expect "2 * x + 2 * 3".
        assert_eq!(s(&ctx, res), "2 * x + 2 * 3"); // Canonical: polynomial order (variables before constants)
    }

    #[test]
    fn test_expand_mul_nested() {
        let mut ctx = Context::new();
        let expr = parse("a * (b + c + d)", &mut ctx).unwrap();
        let res = expand(&mut ctx, expr);
        // a*b + a*c + a*d
        // (b+c)+d -> a*(b+c) + a*d -> (a*b + a*c) + a*d
        let str_res = s(&ctx, res);
        assert!(str_res.contains("a * b"));
        assert!(str_res.contains("a * c"));
        assert!(str_res.contains("a * d"));
    }

    #[test]
    fn test_expand_pow_binomial() {
        let mut ctx = Context::new();
        let expr = parse("(x + 1)^2", &mut ctx).unwrap();
        let res = expand(&mut ctx, expr);
        // x^2 + 2*x*1 + 1^2 -> x^2 + 2*x + 1 (if simplified)
        // Here: x^2 + 2 * (x * 1) + 1
        // Wait, 1^2 is 1? No, expand_pow constructs Pow(1, 2).
        // Unless we have simplification.
        // My implementation:
        // term_a = x^2 (if exp_a=2)
        // term_b = 1 (if exp_b=0)
        // term = x^2 * 1
        // coeff = 1.
        // So x^2 * 1.
        // Middle: 2 * (x^1 * 1^1) = 2 * (x * 1).
        // Last: 1 * (x^0 * 1^2) = 1 * (1 * 1^2).
        // This is very verbose without simplification.
        // But `expand` is supposed to be pure structural expansion.
        // Simplification happens later or we use a smart builder.
        // For now, let's check structure.
        let str_res = s(&ctx, res);
        assert!(str_res.contains("x^2"));
        // assert!(str_res.contains("2 * x")); // Might be 2 * (x * 1)
    }
}
