//! Calculus rules: differentiation, integration, summation, and products.
//!
//! This module is split into submodules:
//! - `differentiation`: symbolic derivative computation
//! - `integration`: symbolic integral computation + helpers
//! - `summation`: finite sum/product evaluation (SumRule, ProductRule)

mod acosh_affine_derivative_presentation;
mod acosh_derivative_routes;
mod acosh_over_sqrt_derivative_presentation;
mod acosh_sqrt_derivative_presentation;
mod acosh_strictly_positive_polynomial_derivative_presentation;
mod affine_inverse_family_post_calculus_presentation;
mod arctan_additive_result_presentation;
mod arctan_by_parts_result_presentation;
mod arctan_companion_result_presentation;
mod arctan_integrand_preservation;
mod arctan_polynomial_integrand_presentation;
mod arctan_sqrt_additive_derivative_presentation;
mod arctan_sqrt_additive_post_calculus_presentation;
mod arctan_sqrt_constant_over_polynomial_presentation;
mod arctan_sqrt_positive_affine_derivative_routes;
mod arctan_sqrt_positive_shift_derivative_presentation;
mod arctan_sqrt_quotient_derivative_presentation;
mod arctan_surd_derivative_presentation;
mod asinh_conditioned_sqrt_derivative_routes;
mod asinh_polynomial_derivative_presentation;
mod asinh_sqrt_constant_over_polynomial_presentation;
mod asinh_sqrt_derivative_presentation;
mod asinh_surd_derivative_presentation;
mod atanh_open_interval_domain;
mod atanh_sqrt_constant_over_polynomial_presentation;
mod atanh_sqrt_derivative_presentation;
mod atanh_sqrt_quotient_derivative_presentation;
mod atanh_surd_derivative_presentation;
mod bounded_inverse_root_quotient_post_calculus_presentation;
mod bounded_inverse_trig_derivative_routes;
mod bounded_inverse_trig_open_interval_domain;
mod bounded_inverse_trig_projection_presentation;
mod bounded_inverse_trig_shifted_sqrt_derivative_presentation;
mod bounded_inverse_trig_sqrt_derivative_presentation;
mod by_parts_integrand_preservation;
mod compact_derivative_presentation_routes;
mod compact_inverse_surd_derivative_routes;
mod constant_scaled_inverse_trig_root_post_calculus_presentation;
mod definite_integration;
mod derivative_integrand_factor_parts;
mod derivative_result_scaling_presentation;
mod diff_domain_undefined_targets;
mod diff_integral_source_post_calculus_presentation;
mod diff_late_derivative_routes;
mod diff_post_calculus_presentation;
mod diff_required_conditions;
mod diff_rule;
mod diff_rule_support;
mod differentiation;
mod direct_symbolic_calculus_presimplify_routes;
mod direct_trig_affine_integrand_presentation;
mod domain_checks;
mod elementary_inverse_function_post_calculus_presentation;
mod elementary_sqrt_derivative_presentation;
mod elementary_variable_term_presentation;
mod exp_by_parts_integrand_presentation;
mod exponential_derivative_presentation;
mod fractional_denominator_power_integrand_preservation;
mod gap_presentation;
mod half_power_sum_result_presentation;
mod hyperbolic_by_parts_integrand_presentation;
mod hyperbolic_power_integrand_presentation;
mod hyperbolic_primitive_derivative_presentation;
mod hyperbolic_reciprocal_derivative_presentation;
mod integral_derivative_arctan_polynomial_routes;
mod integral_derivative_conditioned_return;
mod integral_derivative_direct_trig_affine_routes;
mod integral_derivative_final_presentation_routes;
mod integral_derivative_final_source_routes;
mod integral_derivative_held_presentation_routes;
mod integral_derivative_held_source_routes;
mod integral_derivative_presentation_route;
mod integral_derivative_shortcut_presentation;
mod integral_derivative_shortcut_return_policy;
mod integral_derivative_sqrt_reciprocal_trig_routes;
mod integral_derivative_sqrt_trig_log_routes;
mod integral_derivative_verified_held_inverse_sqrt_routes;
mod integral_derivative_verified_held_polynomial_substitution_routes;
mod integral_derivative_verified_power_inverse_routes;
mod integral_derivative_verified_rational_substitution_routes;
mod integral_derivative_verified_source_routes;
mod integrate_post_calculus_presentation;
mod integrate_rule;
mod integration;
mod integration_antiderivative_verification;
mod integration_arctan_by_parts_result_presentation;
mod integration_conditions;
mod integration_derivative_cofactor_routes;
mod integration_final_result_presentation;
mod integration_fractional_power_result_presentation;
mod integration_inverse_argument_presentation;
mod integration_power_result_preservation;
mod integration_result_pipeline;
mod integration_source_preservation;
mod integration_source_route_hits;
mod integration_sqrt_result_preservation;
mod inverse_hyperbolic_affine_integrand_preservation;
mod inverse_hyperbolic_root_post_calculus_presentation;
mod inverse_hyperbolic_scaled_sqrt_derivative_routes;
mod inverse_reciprocal_trig_affine_abs_derivative_presentation;
mod inverse_reciprocal_trig_positive_quadratic_derivative_presentation;
mod inverse_reciprocal_trig_positive_quadratic_square_presentation;
mod inverse_reciprocal_trig_positive_quadratic_surd_quotient_presentation;
mod inverse_reciprocal_trig_sqrt_derivative_presentation;
mod inverse_sqrt_product_integrand_presentation;
mod inverse_sqrt_product_integrand_preservation;
mod inverse_surd_quotient_derivative_presentation;
mod inverse_tangent_hyperbolic_rational_affine_derivative_presentation;
mod inverse_tangent_polynomial_root_derivative_presentation;
mod inverse_tangent_polynomial_root_post_calculus_presentation;
mod inverse_tangent_reciprocal_sqrt_derivative_presentation;
mod inverse_tangent_reciprocal_sqrt_derivative_routes;
mod inverse_tangent_root_args;
mod inverse_tangent_scaled_root_derivative_presentation;
mod inverse_tangent_scaled_root_derivative_routes;
mod inverse_tangent_scaled_root_quotient_post_calculus_presentation;
mod inverse_tangent_trig_affine_derivative_presentation;
mod inverse_trig_derivative_presentation;
mod ln_sqrt_derivative_routes;
mod ln_sqrt_polynomial_direct_derivative_presentation;
mod ln_sqrt_polynomial_gap_derivative_presentation;
mod ln_sqrt_positive_shift_derivative_presentation;
mod ln_sqrt_shift_derivative_presentation;
mod ln_sum_equal_roots_derivative_presentation;
mod log_by_parts_integrand_presentation;
mod log_derivative_presentation;
mod log_product_integrand_preservation;
mod log_reciprocal_trig_sqrt_derivative_presentation;
mod log_root_derivative_presentation;
mod log_shifted_tan_sqrt_derivative_presentation;
mod log_sqrt_quotient_derivative_presentation;
mod log_sqrt_quotient_derivative_routes;
mod log_sqrt_trig_derivative_routes;
mod negative_half_power_result_presentation;
mod negative_odd_half_power_result_presentation;
mod polynomial_over_sqrt_derivative_presentation;
mod polynomial_power_presentation;
mod polynomial_support;
mod polynomial_times_sqrt_polynomial_derivative_presentation;
mod positive_half_power_result_presentation;
mod positive_quadratic_derivative_routes;
mod positive_quadratic_presentation;
mod positive_quadratic_square_result_presentation;
mod positive_shift_linear_presentation;
mod post_calculus_presentation;
mod presentation_compaction;
mod presentation_utils;
mod primitive_derivative_routes;
mod rational_partial_fraction_integrand_preservation;
mod rationalized_sqrt_result_presentation;
mod reciprocal_sqrt_product_derivative_presentation;
mod reciprocal_trig_derivative_presentation;
mod reciprocal_trig_derivative_product_source;
mod reciprocal_trig_log_domain;
mod result_presentation;
mod result_preservation;
mod result_sensitive_post_calculus_presentation;
mod root_and_inverse_family_post_calculus_presentation;
mod root_required_conditions;
mod scalar_additive_presentation;
mod scalar_numeric_fold_presentation;
mod scalar_positive_quotient_presentation;
mod scalar_presentation;
mod scalar_rational_sqrt_presentation;
mod scalar_scale_presentation;
mod scaled_sqrt_args;
mod self_normalized_surd_quotient_derivative_presentation;
mod shifted_sqrt_args;
mod shifted_sqrt_argument_presentation;
mod shifted_sqrt_derivative_presentation;
mod shifted_sqrt_derivative_routes;
mod signed_factor_presentation;
mod sqrt_additive_generic_derivative_routes;
mod sqrt_additive_result_presentation;
mod sqrt_additive_tan_derivative_presentation;
mod sqrt_additive_tan_inline_derivative_presentation;
mod sqrt_additive_tan_result_presentation;
mod sqrt_additive_tan_term_scan;
mod sqrt_additive_trig_derivative_presentation;
mod sqrt_bounded_trig_positive_shift_derivative_presentation;
mod sqrt_chain_factor_presentation;
mod sqrt_chain_integrand_preservation;
mod sqrt_denominator_result_presentation;
mod sqrt_derivative_post_calculus_presentation;
mod sqrt_early_derivative_routes;
mod sqrt_elementary_derivative_routes;
mod sqrt_elementary_function_derivative_presentation;
mod sqrt_hyperbolic_log_integrand_presentation;
mod sqrt_hyperbolic_result_presentation;
mod sqrt_log_family_post_calculus_presentation;
mod sqrt_polynomial_quotient_derivative_presentation;
mod sqrt_polynomial_scale_presentation;
mod sqrt_product_presentation;
mod sqrt_reciprocal_trig_antiderivative_presentation;
mod sqrt_reciprocal_trig_function_derivative_presentation;
mod sqrt_reciprocal_trig_product_integrand_presentation;
mod sqrt_shifted_log_derivative_presentation;
mod sqrt_small_additive_derivative_presentation;
mod sqrt_trig_log_antiderivative_presentation;
mod sqrt_trig_log_integrand_presentation;
mod sqrt_trig_result_presentation;
mod summation;
mod surd_quotient_args;
mod surd_quotient_derivative_routes;
mod surd_quotient_presentation;
mod tanh_primitive_derivative_presentation;
mod trig_by_parts_integrand_presentation;
mod trig_odd_power_result_presentation;
mod trig_power_integrand_presentation;
mod trig_result_presentation;
mod unary_function_presentation;

pub(crate) use arctan_sqrt_additive_derivative_presentation::{
    arctan_sqrt_additive_tan_polynomial_derivative_inline_presentation_with_domain,
    arctan_sqrt_additive_tan_polynomial_derivative_presentation_with_domain,
    arctan_sqrt_additive_trig_polynomial_derivative_presentation_with_domain,
    arctan_sqrt_small_additive_elementary_derivative_presentation_with_domain,
};
pub(crate) use arctan_sqrt_quotient_derivative_presentation::arctan_sqrt_positive_polynomial_quotient_derivative_for_diff_call;
pub use diff_rule::{DiffRule, IntegralDiffShortcutRule};
pub(crate) use direct_symbolic_calculus_presimplify_routes::try_resolve_direct_symbolic_calculus_before_general_simplify;
pub(crate) use domain_checks::diff_target_known_undefined_over_reals;
use elementary_sqrt_derivative_presentation::signed_elementary_sqrt_polynomial_derivative_presentation;
use elementary_variable_term_presentation::{
    scaled_ln_variable_arg_for_calculus_presentation,
    scaled_sqrt_variable_term_for_calculus_presentation,
};
use exponential_derivative_presentation::sqrt_shifted_exp_derivative_presentation;
pub(crate) use hyperbolic_primitive_derivative_presentation::affine_hyperbolic_odd_primitive_derivative_presentation;
pub(crate) use hyperbolic_reciprocal_derivative_presentation::constant_scaled_hyperbolic_reciprocal_derivative_quotient_presentation_with_domain;
pub use integrate_rule::IntegrateRule;
pub(crate) use integration::{
    is_public_algorithmic_backend_symbolic_indefinite_square_fallback_shape,
    is_public_algorithmic_backend_symbolic_positive_quadratic_fallback_shape,
};
pub(crate) use inverse_reciprocal_trig_positive_quadratic_surd_quotient_presentation::inverse_reciprocal_trig_positive_quadratic_surd_quotient_presentation_with_domain;
pub(crate) use ln_sum_equal_roots_derivative_presentation::ln_sum_of_equal_derivative_roots_derivative_presentation_with_domain;
use log_sqrt_quotient_derivative_presentation::{
    log_over_sqrt_polynomial_derivative_presentation,
    sqrt_over_log_polynomial_derivative_presentation,
};
use polynomial_over_sqrt_derivative_presentation::polynomial_over_sqrt_polynomial_derivative_presentation;
pub(crate) use polynomial_over_sqrt_derivative_presentation::polynomial_over_sqrt_polynomial_derivative_presentation_with_domain;
use polynomial_support::{
    polynomial_is_strictly_positive_everywhere, polynomial_radicand_for_calculus_presentation,
};
pub(crate) use post_calculus_presentation::try_post_calculus_presentation;
pub(crate) use presentation_compaction::compact_double_angle_sine_products_for_calculus_presentation;
use presentation_compaction::{
    compact_numeric_mul_factors_for_calculus_presentation,
    compact_small_power_exponents_for_calculus_presentation,
};
pub(crate) use reciprocal_sqrt_product_derivative_presentation::reciprocal_sqrt_polynomial_product_derivative_presentation_with_domain;
use reciprocal_sqrt_product_derivative_presentation::{
    constant_scaled_inverse_tangent_reciprocal_sqrt_product_derivative_presentation,
    reciprocal_sqrt_polynomial_product_derivative_presentation,
};
pub(crate) use reciprocal_trig_derivative_presentation::{
    constant_scaled_reciprocal_trig_affine_derivative_presentation_with_domain,
    reciprocal_trig_shifted_sqrt_derivative_presentation,
};
pub(crate) use reciprocal_trig_derivative_product_source::{
    constant_scaled_reciprocal_trig_derivative_product_source,
    reciprocal_trig_derivative_integrand_quotient,
};
pub(crate) use result_presentation::try_calculus_result_presentation;
use scalar_presentation::{
    add_one_for_calculus_presentation, add_rational_for_calculus_presentation,
};
pub(crate) use shifted_sqrt_derivative_presentation::sqrt_over_positive_shifted_sqrt_derivative_presentation_with_domain;
use shifted_sqrt_derivative_presentation::{
    reciprocal_positive_shifted_sqrt_derivative, sqrt_over_positive_shifted_sqrt_derivative,
};
pub(crate) use sqrt_additive_tan_derivative_presentation::{
    sqrt_additive_tan_polynomial_derivative_inline_presentation,
    sqrt_additive_tan_polynomial_derivative_presentation,
};
pub(crate) use sqrt_additive_trig_derivative_presentation::sqrt_additive_trig_polynomial_derivative_presentation;
use sqrt_polynomial_quotient_derivative_presentation::{
    sqrt_of_polynomial_quotient_derivative_presentation,
    sqrt_polynomial_quotient_derivative_presentation,
};
pub(crate) use sqrt_polynomial_quotient_derivative_presentation::{
    sqrt_of_polynomial_quotient_derivative_presentation_with_domain,
    sqrt_polynomial_quotient_derivative_presentation_with_domain,
    sqrt_polynomial_quotient_has_powered_expanded_affine_square_denominator,
};
use sqrt_product_presentation::shared_positive_content_sqrt_product_for_calculus_presentation;
use sqrt_shifted_log_derivative_presentation::sqrt_shifted_ln_derivative_presentation;
pub(crate) use sqrt_small_additive_derivative_presentation::sqrt_small_additive_elementary_derivative_presentation_with_domain;
pub(crate) use tanh_primitive_derivative_presentation::diff_target_is_tanh_cubic_sech_fourth_primitive;

pub fn register(simplifier: &mut crate::Simplifier) {
    simplifier.add_rule(Box::new(IntegrateRule));
    simplifier.add_rule(Box::new(IntegralDiffShortcutRule));
    simplifier.add_rule(Box::new(DiffRule));
    simplifier.add_rule(Box::new(summation::SumRule));
    simplifier.add_rule(Box::new(summation::ProductRule));
}
