#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum DeriveTargetForm {
    Simplified,
    IntegratePrepared,
    SolvePrepared,
    FiniteAggregateEvaluated,
    LikeTermsCombined,
    FactorialRewritten,
    InverseTrigRewritten,
    FractionCancelled,
    NestedFractionSimplified,
    RadicalRewritten,
    LogExpanded,
    LogContracted,
    ExponentialRewritten,
    HyperbolicRewritten,
    TrigRewritten,
    TrigExpanded,
    TrigContracted,
    Rationalized,
    FractionExpanded,
    FractionDecomposed,
    FractionCombined,
    FactoredWithDivision { var: String },
    PowerMerged,
    OddHalfPowerExpanded,
    Expanded,
    Collected { var: String },
    Factored,
    Unknown,
}
