use cas_ast::symbol::SymbolId;
use cas_ast::{Equation, ExprId, RelOp, SolutionSet};

/// Dispatch isolation with default kernels while routing arithmetic/function
/// branches through caller-provided callbacks that receive full equation
/// context and start with empty branch-local step vectors.
#[allow(clippy::too_many_arguments)]
pub fn dispatch_isolation_with_default_kernels_and_route_callbacks_with_state<
    T,
    S,
    E,
    FContextRef,
    FContextMut,
    FSimplifyRhs,
    FCollectLinearItem,
    FSimplifyLinearExpr,
    FProveNonzeroStatus,
    FRenderExpr,
    FOnAddRoute,
    FOnSubRoute,
    FOnMulRoute,
    FOnDivRoute,
    FOnPowRoute,
    FOnFunctionRoute,
    FCollectNegatedItem,
    FSolveNegatedRewritten,
    FMapStep,
    FMapUnsupportedError,
>(
    state: &mut T,
    lhs: ExprId,
    rhs: ExprId,
    op: RelOp,
    var: &str,
    context_ref: FContextRef,
    context_mut: FContextMut,
    simplify_rhs: FSimplifyRhs,
    collect_linear_item: FCollectLinearItem,
    simplify_linear_expr: FSimplifyLinearExpr,
    prove_nonzero_status: FProveNonzeroStatus,
    render_expr: FRenderExpr,
    mut on_add_route: FOnAddRoute,
    mut on_sub_route: FOnSubRoute,
    mut on_mul_route: FOnMulRoute,
    mut on_div_route: FOnDivRoute,
    mut on_pow_route: FOnPowRoute,
    mut on_function_route: FOnFunctionRoute,
    collect_negated_item: FCollectNegatedItem,
    solve_negated_rewritten: FSolveNegatedRewritten,
    map_step: FMapStep,
    map_unsupported_error: FMapUnsupportedError,
) -> Result<(SolutionSet, Vec<S>), E>
where
    S: Clone,
    FContextRef: Fn(&mut T) -> &cas_ast::Context,
    FContextMut: Fn(&mut T) -> &mut cas_ast::Context,
    FSimplifyRhs: FnMut(&mut T, ExprId) -> ExprId,
    FCollectLinearItem: FnMut(&mut T) -> bool,
    FSimplifyLinearExpr: FnMut(&mut T, ExprId) -> ExprId,
    FProveNonzeroStatus: FnMut(&mut T, ExprId) -> crate::linear_solution::NonZeroStatus,
    FRenderExpr: Fn(&cas_ast::Context, ExprId) -> String,
    FOnAddRoute: FnMut(
        &mut T,
        ExprId,
        ExprId,
        ExprId,
        ExprId,
        RelOp,
        &str,
        Vec<S>,
    ) -> Result<(SolutionSet, Vec<S>), E>,
    FOnSubRoute: FnMut(
        &mut T,
        ExprId,
        ExprId,
        ExprId,
        RelOp,
        &str,
        Vec<S>,
    ) -> Result<(SolutionSet, Vec<S>), E>,
    FOnMulRoute: FnMut(
        &mut T,
        ExprId,
        ExprId,
        ExprId,
        ExprId,
        RelOp,
        &str,
        Vec<S>,
    ) -> Result<(SolutionSet, Vec<S>), E>,
    FOnDivRoute: FnMut(
        &mut T,
        ExprId,
        ExprId,
        ExprId,
        ExprId,
        RelOp,
        &str,
        Vec<S>,
    ) -> Result<(SolutionSet, Vec<S>), E>,
    FOnPowRoute: FnMut(
        &mut T,
        ExprId,
        ExprId,
        ExprId,
        ExprId,
        RelOp,
        &str,
        Vec<S>,
    ) -> Result<(SolutionSet, Vec<S>), E>,
    FOnFunctionRoute: FnMut(
        &mut T,
        SymbolId,
        Vec<ExprId>,
        ExprId,
        RelOp,
        &str,
        Vec<S>,
    ) -> Result<(SolutionSet, Vec<S>), E>,
    FCollectNegatedItem: FnMut(&mut T) -> bool,
    FSolveNegatedRewritten: FnMut(&mut T, Equation, &str) -> Result<(SolutionSet, Vec<S>), E>,
    FMapStep: FnMut(String, Equation) -> S,
    FMapUnsupportedError: FnMut(&mut T, cas_ast::Expr) -> E,
{
    crate::isolation_dispatch::execute_isolation_dispatch_with_default_isolated_and_negated_entries_and_default_linear_collect_kernels_for_var_and_unified_step_mapper_with_state(
        state,
        lhs,
        rhs,
        op.clone(),
        var,
        context_ref,
        context_mut,
        simplify_rhs,
        collect_linear_item,
        simplify_linear_expr,
        prove_nonzero_status,
        render_expr,
        |state, left, right| on_add_route(state, lhs, left, right, rhs, op.clone(), var, Vec::new()),
        |state, left, right| on_sub_route(state, left, right, rhs, op.clone(), var, Vec::new()),
        |state, left, right| on_mul_route(state, lhs, left, right, rhs, op.clone(), var, Vec::new()),
        |state, left, right| on_div_route(state, lhs, left, right, rhs, op.clone(), var, Vec::new()),
        |state, base, exponent| on_pow_route(state, lhs, base, exponent, rhs, op.clone(), var, Vec::new()),
        |state, fn_id, args| on_function_route(state, fn_id, args, rhs, op.clone(), var, Vec::new()),
        collect_negated_item,
        solve_negated_rewritten,
        map_step,
        map_unsupported_error,
    )
}
