use cas_ast::symbol::SymbolId;
use cas_ast::{Equation, ExprId, RelOp, SolutionSet};

/// Dispatch one isolation step (`lhs op rhs`) using default isolated/negated
/// entries and default linear-collect kernels.
#[allow(clippy::too_many_arguments)]
pub fn dispatch_isolation_with_default_isolated_and_negated_entries_and_default_linear_collect_kernels_for_var_and_unified_step_mapper_with_state<
    T,
    S,
    E,
    FContextRef,
    FContextMut,
    FSimplifyRhs,
    FCollectLinearItem,
    FSimplifyLinearExpr,
    FProveNonzeroStatus,
    FRenderExpr,
    FOnAdd,
    FOnSub,
    FOnMul,
    FOnDiv,
    FOnPow,
    FOnFunction,
    FCollectNegatedItem,
    FSolveNegatedRewritten,
    FMapStep,
    FMapUnsupportedError,
>(
    state: &mut T,
    lhs: ExprId,
    rhs: ExprId,
    op: RelOp,
    var: &str,
    context_ref: FContextRef,
    context_mut: FContextMut,
    simplify_rhs: FSimplifyRhs,
    collect_linear_item: FCollectLinearItem,
    simplify_linear_expr: FSimplifyLinearExpr,
    prove_nonzero_status: FProveNonzeroStatus,
    render_expr: FRenderExpr,
    on_add: FOnAdd,
    on_sub: FOnSub,
    on_mul: FOnMul,
    on_div: FOnDiv,
    on_pow: FOnPow,
    on_function: FOnFunction,
    collect_negated_item: FCollectNegatedItem,
    solve_negated_rewritten: FSolveNegatedRewritten,
    map_step: FMapStep,
    map_unsupported_error: FMapUnsupportedError,
) -> Result<(SolutionSet, Vec<S>), E>
where
    S: Clone,
    FContextRef: Fn(&mut T) -> &cas_ast::Context,
    FContextMut: Fn(&mut T) -> &mut cas_ast::Context,
    FSimplifyRhs: FnMut(&mut T, ExprId) -> ExprId,
    FCollectLinearItem: FnMut(&mut T) -> bool,
    FSimplifyLinearExpr: FnMut(&mut T, ExprId) -> ExprId,
    FProveNonzeroStatus: FnMut(&mut T, ExprId) -> crate::linear_solution::NonZeroStatus,
    FRenderExpr: Fn(&cas_ast::Context, ExprId) -> String,
    FOnAdd: FnMut(&mut T, ExprId, ExprId) -> Result<(SolutionSet, Vec<S>), E>,
    FOnSub: FnMut(&mut T, ExprId, ExprId) -> Result<(SolutionSet, Vec<S>), E>,
    FOnMul: FnMut(&mut T, ExprId, ExprId) -> Result<(SolutionSet, Vec<S>), E>,
    FOnDiv: FnMut(&mut T, ExprId, ExprId) -> Result<(SolutionSet, Vec<S>), E>,
    FOnPow: FnMut(&mut T, ExprId, ExprId) -> Result<(SolutionSet, Vec<S>), E>,
    FOnFunction: FnMut(&mut T, SymbolId, Vec<ExprId>) -> Result<(SolutionSet, Vec<S>), E>,
    FCollectNegatedItem: FnMut(&mut T) -> bool,
    FSolveNegatedRewritten: FnMut(&mut T, Equation, &str) -> Result<(SolutionSet, Vec<S>), E>,
    FMapStep: FnMut(String, Equation) -> S,
    FMapUnsupportedError: FnMut(&mut T, cas_ast::Expr) -> E,
{
    crate::isolation_dispatch::execute_isolation_dispatch_with_default_isolated_and_negated_entries_and_default_linear_collect_kernels_for_var_and_unified_step_mapper_with_state(
        state,
        lhs,
        rhs,
        op,
        var,
        context_ref,
        context_mut,
        simplify_rhs,
        collect_linear_item,
        simplify_linear_expr,
        prove_nonzero_status,
        render_expr,
        on_add,
        on_sub,
        on_mul,
        on_div,
        on_pow,
        on_function,
        collect_negated_item,
        solve_negated_rewritten,
        map_step,
        map_unsupported_error,
    )
}
