pub use solve_runtime_flow_preflight_prepare_residual::prepare_equation_for_strategy_with_default_residual_acceptance_and_state;
pub use solve_runtime_flow_preflight_prepare_structural::prepare_equation_for_strategy_with_default_structural_recompose_and_cancel_and_default_residual_acceptance_with_state;

#[path = "solve_runtime_flow_preflight_prepare_residual.rs"]
mod solve_runtime_flow_preflight_prepare_residual;
#[path = "solve_runtime_flow_preflight_prepare_structural.rs"]
mod solve_runtime_flow_preflight_prepare_structural;
