//! Isolation arithmetic/function/pow runtime kernels extracted from
//! `solve_runtime_flow_isolation`.

use cas_ast::symbol::SymbolId;
use cas_ast::{Equation, ExprId, RelOp, SolutionSet};

#[allow(clippy::too_many_arguments)]
pub fn apply_function_isolation_with_default_kernels_and_runtime_trace_and_unified_step_mapper_for_var_with_state<
    T,
    S,
    E,
    FCollectItems,
    FContextRef,
    FContextMut,
    FRenderExpr,
    FIsolateRecursive,
    FSimplifyWithTrace,
    FMapStep,
    FMapVariableNotFound,
    FMapUnsupportedInverse,
    FMapUnknownFunction,
>(
    state: &mut T,
    fn_id: SymbolId,
    args: &[ExprId],
    rhs: ExprId,
    op: RelOp,
    var: &str,
    steps: Vec<S>,
    mut collect_items: FCollectItems,
    context_ref: FContextRef,
    context_mut: FContextMut,
    render_expr: FRenderExpr,
    isolate_recursive: FIsolateRecursive,
    simplify_with_trace: FSimplifyWithTrace,
    map_step: FMapStep,
    map_variable_not_found: FMapVariableNotFound,
    map_unsupported_inverse: FMapUnsupportedInverse,
    map_unknown_function: FMapUnknownFunction,
) -> Result<(SolutionSet, Vec<S>), E>
where
    S: Clone,
    FCollectItems: FnMut(&mut T) -> bool,
    FContextRef: Fn(&mut T) -> &cas_ast::Context,
    FContextMut: Fn(&mut T) -> &mut cas_ast::Context,
    FRenderExpr: Fn(&cas_ast::Context, ExprId) -> String,
    FIsolateRecursive: FnMut(&mut T, ExprId, ExprId, RelOp) -> Result<(SolutionSet, Vec<S>), E>,
    FSimplifyWithTrace: FnMut(&mut T, ExprId) -> (ExprId, Vec<(String, ExprId)>),
    FMapStep: FnMut(String, Equation) -> S,
    FMapVariableNotFound: FnMut(&mut T, &str) -> E,
    FMapUnsupportedInverse: FnMut(&mut T, SymbolId, usize, &str) -> E,
    FMapUnknownFunction: FnMut(&mut T, &str) -> E,
{
    let include_items = collect_items(state);
    crate::isolation_functions::execute_function_isolation_with_default_kernels_and_unified_step_mapper_for_var_with_state(
        state,
        fn_id,
        args,
        rhs,
        op,
        var,
        include_items,
        steps,
        context_ref,
        context_mut,
        render_expr,
        isolate_recursive,
        simplify_with_trace,
        map_step,
        map_variable_not_found,
        map_unsupported_inverse,
        map_unknown_function,
    )
}

/// Execute function isolation with default kernels and a standard unsupported
/// inverse error message built from function symbol name.
#[allow(clippy::too_many_arguments)]
pub fn apply_function_isolation_with_default_kernels_and_runtime_trace_and_default_unsupported_inverse_message_with_state<
    T,
    S,
    E,
    FCollectItems,
    FContextRef,
    FContextMut,
    FRenderExpr,
    FIsolateRecursive,
    FSimplifyWithTrace,
    FMapStep,
    FSymName,
    FMapVariableNotFound,
    FMapIsolationError,
    FMapUnknownFunction,
>(
    state: &mut T,
    fn_id: SymbolId,
    args: &[ExprId],
    rhs: ExprId,
    op: RelOp,
    var: &str,
    steps: Vec<S>,
    collect_items: FCollectItems,
    context_ref: FContextRef,
    context_mut: FContextMut,
    render_expr: FRenderExpr,
    isolate_recursive: FIsolateRecursive,
    simplify_with_trace: FSimplifyWithTrace,
    map_step: FMapStep,
    mut sym_name: FSymName,
    map_variable_not_found: FMapVariableNotFound,
    mut map_isolation_error: FMapIsolationError,
    map_unknown_function: FMapUnknownFunction,
) -> Result<(SolutionSet, Vec<S>), E>
where
    S: Clone,
    FCollectItems: FnMut(&mut T) -> bool,
    FContextRef: Fn(&mut T) -> &cas_ast::Context,
    FContextMut: Fn(&mut T) -> &mut cas_ast::Context,
    FRenderExpr: Fn(&cas_ast::Context, ExprId) -> String,
    FIsolateRecursive: FnMut(&mut T, ExprId, ExprId, RelOp) -> Result<(SolutionSet, Vec<S>), E>,
    FSimplifyWithTrace: FnMut(&mut T, ExprId) -> (ExprId, Vec<(String, ExprId)>),
    FMapStep: FnMut(String, Equation) -> S,
    FSymName: FnMut(&mut T, SymbolId) -> String,
    FMapVariableNotFound: FnMut(&mut T, &str) -> E,
    FMapIsolationError: FnMut(&mut T, &str, String) -> E,
    FMapUnknownFunction: FnMut(&mut T, &str) -> E,
{
    apply_function_isolation_with_default_kernels_and_runtime_trace_and_unified_step_mapper_for_var_with_state(
        state,
        fn_id,
        args,
        rhs,
        op,
        var,
        steps,
        collect_items,
        context_ref,
        context_mut,
        render_expr,
        isolate_recursive,
        simplify_with_trace,
        map_step,
        map_variable_not_found,
        |state, unsupported_fn_id, arity, unsupported_var| {
            let fn_name = sym_name(state, unsupported_fn_id);
            map_isolation_error(
                state,
                unsupported_var,
                format!(
                    "Cannot invert function '{}' with {} arguments",
                    fn_name, arity
                ),
            )
        },
        map_unknown_function,
    )
}

/// Execute function isolation with default unsupported-inverse messaging and a
/// single recursive equation solver reused for all inner isolate calls.
#[allow(clippy::too_many_arguments)]
pub fn apply_function_isolation_with_default_kernels_and_runtime_trace_and_default_unsupported_inverse_message_and_recursive_equation_solver_with_state<
    T,
    S,
    E,
    FCollectItems,
    FContextRef,
    FContextMut,
    FRenderExpr,
    FSolveEquation,
    FSimplifyWithTrace,
    FMapStep,
    FSymName,
    FMapVariableNotFound,
    FMapIsolationError,
    FMapUnknownFunction,
>(
    state: &mut T,
    fn_id: SymbolId,
    args: &[ExprId],
    rhs: ExprId,
    op: RelOp,
    var: &str,
    steps: Vec<S>,
    collect_items: FCollectItems,
    context_ref: FContextRef,
    context_mut: FContextMut,
    render_expr: FRenderExpr,
    solve_equation: FSolveEquation,
    simplify_with_trace: FSimplifyWithTrace,
    map_step: FMapStep,
    sym_name: FSymName,
    map_variable_not_found: FMapVariableNotFound,
    map_isolation_error: FMapIsolationError,
    map_unknown_function: FMapUnknownFunction,
) -> Result<(SolutionSet, Vec<S>), E>
where
    S: Clone,
    FCollectItems: FnMut(&mut T) -> bool,
    FContextRef: Fn(&mut T) -> &cas_ast::Context,
    FContextMut: Fn(&mut T) -> &mut cas_ast::Context,
    FRenderExpr: Fn(&cas_ast::Context, ExprId) -> String,
    FSolveEquation: FnMut(&mut T, Equation, &str) -> Result<(SolutionSet, Vec<S>), E>,
    FSimplifyWithTrace: FnMut(&mut T, ExprId) -> (ExprId, Vec<(String, ExprId)>),
    FMapStep: FnMut(String, Equation) -> S,
    FSymName: FnMut(&mut T, SymbolId) -> String,
    FMapVariableNotFound: FnMut(&mut T, &str) -> E,
    FMapIsolationError: FnMut(&mut T, &str, String) -> E,
    FMapUnknownFunction: FnMut(&mut T, &str) -> E,
{
    let solve_equation = std::cell::RefCell::new(solve_equation);
    apply_function_isolation_with_default_kernels_and_runtime_trace_and_default_unsupported_inverse_message_with_state(
        state,
        fn_id,
        args,
        rhs,
        op,
        var,
        steps,
        collect_items,
        context_ref,
        context_mut,
        render_expr,
        |state, lhs_expr, rhs_expr, inner_op| {
            (solve_equation.borrow_mut())(
                state,
                Equation {
                    lhs: lhs_expr,
                    rhs: rhs_expr,
                    op: inner_op,
                },
                var,
            )
        },
        simplify_with_trace,
        map_step,
        sym_name,
        map_variable_not_found,
        map_isolation_error,
        map_unknown_function,
    )
}

/// Execute additive isolation (`left + right = rhs`) with default arithmetic
/// kernels and runtime-provided callbacks.
#[allow(clippy::too_many_arguments)]
pub fn apply_add_isolation_strategy_with_default_kernels_and_unified_step_mapper_with_state<
    T,
    S,
    E,
    FCollectItem,
    FContextRef,
    FContextMut,
    FRenderExpr,
    FSimplifyExpr,
    FProveNonzeroStatus,
    FIsolateRewritten,
    FMapStep,
>(
    state: &mut T,
    lhs: ExprId,
    left: ExprId,
    right: ExprId,
    rhs: ExprId,
    op: RelOp,
    var: &str,
    steps: Vec<S>,
    mut collect_item: FCollectItem,
    context_ref: FContextRef,
    context_mut: FContextMut,
    render_expr: FRenderExpr,
    simplify_expr: FSimplifyExpr,
    prove_nonzero_status: FProveNonzeroStatus,
    isolate_rewritten: FIsolateRewritten,
    map_step: FMapStep,
) -> Result<(SolutionSet, Vec<S>), E>
where
    FCollectItem: FnMut(&mut T) -> bool,
    FContextRef: Fn(&mut T) -> &cas_ast::Context,
    FContextMut: Fn(&mut T) -> &mut cas_ast::Context,
    FRenderExpr: Fn(&cas_ast::Context, ExprId) -> String,
    FSimplifyExpr: FnMut(&mut T, ExprId) -> ExprId,
    FProveNonzeroStatus: FnMut(&mut T, ExprId) -> crate::linear_solution::NonZeroStatus,
    FIsolateRewritten: FnMut(&mut T, Equation) -> Result<(SolutionSet, Vec<S>), E>,
    FMapStep: FnMut(String, Equation) -> S,
{
    let include_item = collect_item(state);
    crate::isolation_arithmetic::execute_add_isolation_pipeline_with_default_factored_linear_collect_and_unified_step_mapper_with_state(
        state,
        lhs,
        left,
        right,
        rhs,
        op,
        var,
        include_item,
        steps,
        context_ref,
        context_mut,
        render_expr,
        simplify_expr,
        prove_nonzero_status,
        isolate_rewritten,
        map_step,
    )
}

/// Execute subtractive isolation (`left - right = rhs`) with default arithmetic
/// kernels and runtime-provided callbacks.
#[allow(clippy::too_many_arguments)]
pub fn apply_sub_isolation_strategy_with_default_kernels_and_unified_step_mapper_with_state<
    T,
    S,
    E,
    FCollectItem,
    FContextRef,
    FContextMut,
    FRenderExpr,
    FSimplifyExpr,
    FIsolateRewritten,
    FMapStep,
>(
    state: &mut T,
    left: ExprId,
    right: ExprId,
    rhs: ExprId,
    op: RelOp,
    var: &str,
    steps: Vec<S>,
    mut collect_item: FCollectItem,
    context_ref: FContextRef,
    context_mut: FContextMut,
    render_expr: FRenderExpr,
    simplify_expr: FSimplifyExpr,
    isolate_rewritten: FIsolateRewritten,
    map_step: FMapStep,
) -> Result<(SolutionSet, Vec<S>), E>
where
    FCollectItem: FnMut(&mut T) -> bool,
    FContextRef: Fn(&mut T) -> &cas_ast::Context,
    FContextMut: Fn(&mut T) -> &mut cas_ast::Context,
    FRenderExpr: Fn(&cas_ast::Context, ExprId) -> String,
    FSimplifyExpr: FnMut(&mut T, ExprId) -> ExprId,
    FIsolateRewritten: FnMut(&mut T, Equation) -> Result<(SolutionSet, Vec<S>), E>,
    FMapStep: FnMut(String, Equation) -> S,
{
    let include_item = collect_item(state);
    crate::isolation_arithmetic::execute_sub_isolation_pipeline_with_default_plan_and_unified_step_mapper_with_state(
        state,
        left,
        right,
        rhs,
        op,
        var,
        include_item,
        steps,
        context_ref,
        context_mut,
        render_expr,
        simplify_expr,
        isolate_rewritten,
        map_step,
    )
}

/// Execute multiplicative isolation (`left * right = rhs`) with default
/// arithmetic kernels and runtime-provided callbacks.
#[allow(clippy::too_many_arguments)]
pub fn apply_mul_isolation_strategy_with_default_kernels_and_unified_step_mapper_with_state<
    T,
    S,
    E,
    FCollectItem,
    FContextRef,
    FContextMut,
    FSolveSplitCase,
    FSimplifyExpr,
    FProveNonzeroStatus,
    FIsKnownNegative,
    FRenderExpr,
    FIsolateRewritten,
    FMapStep,
>(
    state: &mut T,
    lhs: ExprId,
    left: ExprId,
    right: ExprId,
    rhs: ExprId,
    op: RelOp,
    var: &str,
    steps: Vec<S>,
    mut collect_item: FCollectItem,
    context_ref: FContextRef,
    context_mut: FContextMut,
    solve_split_case: FSolveSplitCase,
    simplify_expr: FSimplifyExpr,
    prove_nonzero_status: FProveNonzeroStatus,
    is_known_negative: FIsKnownNegative,
    render_expr: FRenderExpr,
    isolate_rewritten: FIsolateRewritten,
    map_step: FMapStep,
) -> Result<(SolutionSet, Vec<S>), E>
where
    FCollectItem: FnMut(&mut T) -> bool,
    FContextRef: Fn(&mut T) -> &cas_ast::Context,
    FContextMut: Fn(&mut T) -> &mut cas_ast::Context,
    FSolveSplitCase: FnMut(&mut T, &Equation) -> Result<(SolutionSet, Vec<S>), E>,
    FSimplifyExpr: FnMut(&mut T, ExprId) -> ExprId,
    FProveNonzeroStatus: FnMut(&mut T, ExprId) -> crate::linear_solution::NonZeroStatus,
    FIsKnownNegative: FnMut(&mut T, ExprId) -> bool,
    FRenderExpr: Fn(&cas_ast::Context, ExprId) -> String,
    FIsolateRewritten: FnMut(&mut T, Equation) -> Result<(SolutionSet, Vec<S>), E>,
    FMapStep: FnMut(String, Equation) -> S,
{
    let include_item = collect_item(state);
    crate::isolation_arithmetic::execute_mul_isolation_pipeline_with_default_additive_linear_collect_and_unified_step_mapper_with_state(
        state,
        lhs,
        left,
        right,
        rhs,
        op,
        var,
        include_item,
        steps,
        context_ref,
        context_mut,
        solve_split_case,
        simplify_expr,
        prove_nonzero_status,
        is_known_negative,
        render_expr,
        isolate_rewritten,
        map_step,
    )
}

/// Execute divisive isolation (`numerator / denominator = rhs`) with default
/// arithmetic kernels and runtime-provided callbacks.
#[allow(clippy::too_many_arguments)]
pub fn apply_div_isolation_strategy_with_default_kernels_and_unified_step_mapper_with_state<
    T,
    S,
    E,
    FCollectNumeratorItems,
    FCollectDenominatorItems,
    FContextRef,
    FContextMut,
    FIsKnownNegative,
    FRenderExpr,
    FSimplifyExpr,
    FIsolateRewritten,
    FProveNonzeroStatus,
    FMapStep,
>(
    state: &mut T,
    lhs: ExprId,
    numerator: ExprId,
    denominator: ExprId,
    rhs: ExprId,
    op: RelOp,
    var: &str,
    steps: Vec<S>,
    mut collect_numerator_items: FCollectNumeratorItems,
    mut collect_denominator_items: FCollectDenominatorItems,
    context_ref: FContextRef,
    context_mut: FContextMut,
    is_known_negative: FIsKnownNegative,
    render_expr: FRenderExpr,
    simplify_expr: FSimplifyExpr,
    isolate_rewritten: FIsolateRewritten,
    prove_nonzero_status: FProveNonzeroStatus,
    map_step: FMapStep,
) -> Result<(SolutionSet, Vec<S>), E>
where
    S: Clone,
    FCollectNumeratorItems: FnMut(&mut T) -> bool,
    FCollectDenominatorItems: FnMut(&mut T) -> bool,
    FContextRef: Fn(&mut T) -> &cas_ast::Context,
    FContextMut: Fn(&mut T) -> &mut cas_ast::Context,
    FIsKnownNegative: FnMut(&mut T, ExprId) -> bool,
    FRenderExpr: Fn(&cas_ast::Context, ExprId) -> String,
    FSimplifyExpr: FnMut(&mut T, ExprId) -> ExprId,
    FIsolateRewritten: FnMut(&mut T, &Equation) -> Result<(SolutionSet, Vec<S>), E>,
    FProveNonzeroStatus: FnMut(&mut T, ExprId) -> crate::linear_solution::NonZeroStatus,
    FMapStep: FnMut(String, Equation) -> S,
{
    let include_numerator_items = collect_numerator_items(state);
    let include_denominator_items = collect_denominator_items(state);
    crate::isolation_arithmetic::execute_div_isolation_pipeline_with_default_reciprocal_fallback_and_unified_step_mapper_with_state(
        state,
        lhs,
        numerator,
        denominator,
        rhs,
        op,
        var,
        include_numerator_items,
        include_denominator_items,
        steps,
        context_ref,
        context_mut,
        is_known_negative,
        render_expr,
        simplify_expr,
        isolate_rewritten,
        prove_nonzero_status,
        map_step,
    )
}

/// Build a runtime power-isolation config by querying include-item hooks from
/// mutable state.
pub fn build_pow_isolation_runtime_config_with_state<
    T,
    TTacticOptions,
    FCollectItem,
    FBuildTacticOptions,
>(
    state: &mut T,
    mode: crate::log_domain::DomainModeKind,
    wildcard_scope: bool,
    value_domain_real_only: bool,
    budget: crate::solve_budget::SolveBudget,
    mut collect_item: FCollectItem,
    build_tactic_options: FBuildTacticOptions,
) -> crate::strategy_options::PowIsolationRuntimeConfig<TTacticOptions>
where
    FCollectItem: FnMut(&mut T) -> bool,
    FBuildTacticOptions: FnOnce() -> TTacticOptions,
{
    crate::strategy_options::pow_runtime_config_with(
        mode,
        wildcard_scope,
        value_domain_real_only,
        budget,
        || collect_item(state),
        build_tactic_options,
    )
}

/// Execute power isolation with a default runtime config built from state
/// (`mode`, `wildcard_scope`, `value_domain_real_only`, `budget`) and then
/// delegated to the core pow kernel pipeline.
#[allow(clippy::too_many_arguments)]
pub fn apply_pow_isolation_with_default_runtime_config_and_unified_step_mapper_for_var_with_state<
    T,
    S,
    E,
    TTacticOptions,
    FCollectItem,
    FBuildTacticOptions,
    FContextRef,
    FContextMut,
    FRenderExpr,
    FIsolateBase,
    FSimplifyShortcut,
    FClearBlockedHints,
    FSimplifyWithTactic,
    FClassifyDecision,
    FSolveShortcut,
    FMapStep,
    FMapEnsureError,
    FVisitAssumption,
    FTryGuardedSolve,
    FRegisterBlockedHint,
    FMapUnsupportedErr,
    FSolveRewrite,
>(
    state: &mut T,
    lhs: ExprId,
    base: ExprId,
    exponent: ExprId,
    rhs: ExprId,
    op: RelOp,
    var: &str,
    mode: crate::log_domain::DomainModeKind,
    wildcard_scope: bool,
    value_domain_real_only: bool,
    budget: crate::solve_budget::SolveBudget,
    collect_item: FCollectItem,
    build_tactic_options: FBuildTacticOptions,
    existing_steps: Vec<S>,
    context_ref: FContextRef,
    context_mut: FContextMut,
    render_expr: FRenderExpr,
    isolate_base: FIsolateBase,
    simplify_shortcut: FSimplifyShortcut,
    clear_blocked_hints: FClearBlockedHints,
    simplify_with_tactic: FSimplifyWithTactic,
    classify_decision: FClassifyDecision,
    solve_shortcut: FSolveShortcut,
    map_step: FMapStep,
    map_ensure_error: FMapEnsureError,
    visit_assumption: FVisitAssumption,
    try_guarded_solve: FTryGuardedSolve,
    register_blocked_hint: FRegisterBlockedHint,
    map_unsupported_err: FMapUnsupportedErr,
    solve_rewrite: FSolveRewrite,
) -> Result<(SolutionSet, Vec<S>), E>
where
    S: Clone,
    FCollectItem: FnMut(&mut T) -> bool,
    FBuildTacticOptions: FnOnce() -> TTacticOptions,
    FContextRef: Fn(&mut T) -> &cas_ast::Context,
    FContextMut: Fn(&mut T) -> &mut cas_ast::Context,
    FRenderExpr: Fn(&cas_ast::Context, ExprId) -> String,
    FIsolateBase: FnMut(&mut T, ExprId, ExprId, RelOp) -> Result<(SolutionSet, Vec<S>), E>,
    FSimplifyShortcut: FnMut(&mut T, ExprId) -> ExprId,
    FClearBlockedHints: FnMut(&mut T),
    FSimplifyWithTactic: FnMut(&mut T, ExprId, &TTacticOptions) -> ExprId,
    FClassifyDecision: FnMut(&mut T, ExprId, ExprId) -> crate::log_domain::LogSolveDecision,
    FSolveShortcut: FnMut(&mut T, ExprId, RelOp) -> Result<(SolutionSet, Vec<S>), E>,
    FMapStep: FnMut(String, Equation) -> S,
    FMapEnsureError: FnMut(&str, &'static str) -> E,
    FVisitAssumption: FnMut(&cas_ast::Context, crate::log_domain::LogAssumption),
    FTryGuardedSolve: FnMut(&mut T, &Equation) -> Option<SolutionSet>,
    FRegisterBlockedHint: FnMut(&cas_ast::Context, crate::solve_outcome::LogBlockedHintRecord),
    FMapUnsupportedErr: FnMut(&'static str) -> E,
    FSolveRewrite: FnMut(&mut T, &Equation) -> Result<(SolutionSet, Vec<S>), E>,
{
    let collect_item = std::cell::RefCell::new(collect_item);
    let config = build_pow_isolation_runtime_config_with_state(
        state,
        mode,
        wildcard_scope,
        value_domain_real_only,
        budget,
        |state| (collect_item.borrow_mut())(state),
        build_tactic_options,
    );

    execute_pow_isolation_with_runtime_config_and_unified_step_mapper_for_var_with_state(
        state,
        lhs,
        base,
        exponent,
        rhs,
        op,
        var,
        config,
        existing_steps,
        context_ref,
        context_mut,
        render_expr,
        isolate_base,
        simplify_shortcut,
        clear_blocked_hints,
        simplify_with_tactic,
        |state| (collect_item.borrow_mut())(state),
        classify_decision,
        solve_shortcut,
        map_step,
        map_ensure_error,
        visit_assumption,
        try_guarded_solve,
        register_blocked_hint,
        map_unsupported_err,
        solve_rewrite,
    )
}

/// Execute power isolation with default runtime config and a single recursive
/// equation solver callback reused across base/shortcut/rewrite/guarded paths.
#[allow(clippy::too_many_arguments)]
pub fn apply_pow_isolation_with_default_runtime_config_and_recursive_equation_solver_with_state<
    T,
    S,
    E,
    TTacticOptions,
    FCollectItem,
    FBuildTacticOptions,
    FContextRef,
    FContextMut,
    FRenderExpr,
    FSimplifyShortcut,
    FClearBlockedHints,
    FSimplifyWithTactic,
    FClassifyDecision,
    FSolveEquation,
    FMapStep,
    FMapEnsureError,
    FVisitAssumption,
    FRegisterBlockedHint,
    FMapUnsupportedErr,
>(
    state: &mut T,
    lhs: ExprId,
    base: ExprId,
    exponent: ExprId,
    rhs: ExprId,
    op: RelOp,
    var: &str,
    mode: crate::log_domain::DomainModeKind,
    wildcard_scope: bool,
    value_domain_real_only: bool,
    budget: crate::solve_budget::SolveBudget,
    collect_item: FCollectItem,
    build_tactic_options: FBuildTacticOptions,
    existing_steps: Vec<S>,
    context_ref: FContextRef,
    context_mut: FContextMut,
    render_expr: FRenderExpr,
    simplify_shortcut: FSimplifyShortcut,
    clear_blocked_hints: FClearBlockedHints,
    simplify_with_tactic: FSimplifyWithTactic,
    classify_decision: FClassifyDecision,
    solve_equation: FSolveEquation,
    map_step: FMapStep,
    map_ensure_error: FMapEnsureError,
    visit_assumption: FVisitAssumption,
    register_blocked_hint: FRegisterBlockedHint,
    map_unsupported_err: FMapUnsupportedErr,
) -> Result<(SolutionSet, Vec<S>), E>
where
    S: Clone,
    FCollectItem: FnMut(&mut T) -> bool,
    FBuildTacticOptions: FnOnce() -> TTacticOptions,
    FContextRef: Fn(&mut T) -> &cas_ast::Context,
    FContextMut: Fn(&mut T) -> &mut cas_ast::Context,
    FRenderExpr: Fn(&cas_ast::Context, ExprId) -> String,
    FSimplifyShortcut: FnMut(&mut T, ExprId) -> ExprId,
    FClearBlockedHints: FnMut(&mut T),
    FSimplifyWithTactic: FnMut(&mut T, ExprId, &TTacticOptions) -> ExprId,
    FClassifyDecision: FnMut(&mut T, ExprId, ExprId) -> crate::log_domain::LogSolveDecision,
    FSolveEquation: FnMut(&mut T, Equation, &str) -> Result<(SolutionSet, Vec<S>), E>,
    FMapStep: FnMut(String, Equation) -> S,
    FMapEnsureError: FnMut(&str, &'static str) -> E,
    FVisitAssumption: FnMut(&cas_ast::Context, crate::log_domain::LogAssumption),
    FRegisterBlockedHint: FnMut(&cas_ast::Context, crate::solve_outcome::LogBlockedHintRecord),
    FMapUnsupportedErr: FnMut(&'static str) -> E,
{
    let solve_equation = std::cell::RefCell::new(solve_equation);
    apply_pow_isolation_with_default_runtime_config_and_unified_step_mapper_for_var_with_state(
        state,
        lhs,
        base,
        exponent,
        rhs,
        op,
        var,
        mode,
        wildcard_scope,
        value_domain_real_only,
        budget,
        collect_item,
        build_tactic_options,
        existing_steps,
        context_ref,
        context_mut,
        render_expr,
        |state, iso_lhs, iso_rhs, iso_op| {
            (solve_equation.borrow_mut())(
                state,
                Equation {
                    lhs: iso_lhs,
                    rhs: iso_rhs,
                    op: iso_op,
                },
                var,
            )
        },
        simplify_shortcut,
        clear_blocked_hints,
        simplify_with_tactic,
        classify_decision,
        |state, shortcut_rhs, shortcut_op| {
            (solve_equation.borrow_mut())(
                state,
                Equation {
                    lhs: exponent,
                    rhs: shortcut_rhs,
                    op: shortcut_op,
                },
                var,
            )
        },
        map_step,
        map_ensure_error,
        visit_assumption,
        |state, equation| {
            (solve_equation.borrow_mut())(state, equation.clone(), var)
                .ok()
                .map(|(solutions, _)| solutions)
        },
        register_blocked_hint,
        map_unsupported_err,
        |state, equation| (solve_equation.borrow_mut())(state, equation.clone(), var),
    )
}

/// Execute power isolation (`base^exponent = rhs`) with one runtime config
/// and default unified-step mapping in the core kernel.
#[allow(clippy::too_many_arguments)]
pub fn execute_pow_isolation_with_runtime_config_and_unified_step_mapper_for_var_with_state<
    T,
    S,
    E,
    TTacticOptions,
    FContextRef,
    FContextMut,
    FRenderExpr,
    FIsolateBase,
    FSimplifyShortcut,
    FClearBlockedHints,
    FSimplifyWithTactic,
    FCollectItem,
    FClassifyDecision,
    FSolveShortcut,
    FMapStep,
    FMapEnsureError,
    FVisitAssumption,
    FTryGuardedSolve,
    FRegisterBlockedHint,
    FMapUnsupportedErr,
    FSolveRewrite,
>(
    state: &mut T,
    lhs: ExprId,
    base: ExprId,
    exponent: ExprId,
    rhs: ExprId,
    op: RelOp,
    var: &str,
    config: crate::strategy_options::PowIsolationRuntimeConfig<TTacticOptions>,
    existing_steps: Vec<S>,
    context_ref: FContextRef,
    context_mut: FContextMut,
    render_expr: FRenderExpr,
    isolate_base: FIsolateBase,
    simplify_shortcut: FSimplifyShortcut,
    clear_blocked_hints: FClearBlockedHints,
    mut simplify_with_tactic: FSimplifyWithTactic,
    collect_item: FCollectItem,
    classify_decision: FClassifyDecision,
    solve_shortcut: FSolveShortcut,
    map_step: FMapStep,
    map_ensure_error: FMapEnsureError,
    visit_assumption: FVisitAssumption,
    try_guarded_solve: FTryGuardedSolve,
    register_blocked_hint: FRegisterBlockedHint,
    map_unsupported_err: FMapUnsupportedErr,
    solve_rewrite: FSolveRewrite,
) -> Result<(SolutionSet, Vec<S>), E>
where
    S: Clone,
    FContextRef: Fn(&mut T) -> &cas_ast::Context,
    FContextMut: Fn(&mut T) -> &mut cas_ast::Context,
    FRenderExpr: Fn(&cas_ast::Context, ExprId) -> String,
    FIsolateBase: FnMut(&mut T, ExprId, ExprId, RelOp) -> Result<(SolutionSet, Vec<S>), E>,
    FSimplifyShortcut: FnMut(&mut T, ExprId) -> ExprId,
    FClearBlockedHints: FnMut(&mut T),
    FSimplifyWithTactic: FnMut(&mut T, ExprId, &TTacticOptions) -> ExprId,
    FCollectItem: FnMut(&mut T) -> bool,
    FClassifyDecision: FnMut(&mut T, ExprId, ExprId) -> crate::log_domain::LogSolveDecision,
    FSolveShortcut: FnMut(&mut T, ExprId, RelOp) -> Result<(SolutionSet, Vec<S>), E>,
    FMapStep: FnMut(String, Equation) -> S,
    FMapEnsureError: FnMut(&str, &'static str) -> E,
    FVisitAssumption: FnMut(&cas_ast::Context, crate::log_domain::LogAssumption),
    FTryGuardedSolve: FnMut(&mut T, &Equation) -> Option<SolutionSet>,
    FRegisterBlockedHint: FnMut(&cas_ast::Context, crate::solve_outcome::LogBlockedHintRecord),
    FMapUnsupportedErr: FnMut(&'static str) -> E,
    FSolveRewrite: FnMut(&mut T, &Equation) -> Result<(SolutionSet, Vec<S>), E>,
{
    let crate::strategy_options::PowIsolationRuntimeConfig {
        kernel,
        tactic_opts,
    } = config;
    crate::isolation_power::execute_pow_isolation_with_kernel_config_and_unified_step_mapper_for_var_with_state(
        state,
        lhs,
        base,
        exponent,
        rhs,
        op,
        var,
        kernel,
        existing_steps,
        context_ref,
        context_mut,
        render_expr,
        isolate_base,
        simplify_shortcut,
        clear_blocked_hints,
        |state, expr| simplify_with_tactic(state, expr, &tactic_opts),
        collect_item,
        classify_decision,
        solve_shortcut,
        map_step,
        map_ensure_error,
        visit_assumption,
        try_guarded_solve,
        register_blocked_hint,
        map_unsupported_err,
        solve_rewrite,
    )
}
