//! Isolation runtime wrappers extracted from `solve_runtime_flow`.

pub use solve_runtime_flow_isolation_custom_pow::dispatch_isolation_with_default_kernels_and_default_arithmetic_routes_and_custom_pow_function_with_state;
pub use solve_runtime_flow_isolation_default_routes::dispatch_isolation_with_default_kernels_and_default_arithmetic_pow_function_routes_with_state;
pub use solve_runtime_flow_isolation_dispatch_base::dispatch_isolation_with_default_isolated_and_negated_entries_and_default_linear_collect_kernels_for_var_and_unified_step_mapper_with_state;
pub use solve_runtime_flow_isolation_route_callbacks::dispatch_isolation_with_default_kernels_and_route_callbacks_with_state;
#[path = "solve_runtime_flow_isolation_custom_pow.rs"]
mod solve_runtime_flow_isolation_custom_pow;
#[path = "solve_runtime_flow_isolation_default_routes.rs"]
mod solve_runtime_flow_isolation_default_routes;
#[path = "solve_runtime_flow_isolation_dispatch_base.rs"]
mod solve_runtime_flow_isolation_dispatch_base;
#[path = "solve_runtime_flow_isolation_route_callbacks.rs"]
mod solve_runtime_flow_isolation_route_callbacks;
