use super::solve_runtime_flow_isolation_pow_core::{
    build_pow_isolation_runtime_config_with_state,
    execute_pow_isolation_with_runtime_config_and_unified_step_mapper_for_var_with_state,
};
use cas_ast::{Equation, ExprId, RelOp, SolutionSet};

/// Execute power isolation with a default runtime config built from state
/// (`mode`, `wildcard_scope`, `value_domain_real_only`, `budget`) and then
/// delegated to the core pow kernel pipeline.
#[allow(clippy::too_many_arguments)]
pub fn apply_pow_isolation_with_default_runtime_config_and_unified_step_mapper_for_var_with_state<
    T,
    S,
    E,
    TTacticOptions,
    FCollectItem,
    FBuildTacticOptions,
    FContextRef,
    FContextMut,
    FRenderExpr,
    FIsolateBase,
    FSimplifyShortcut,
    FClearBlockedHints,
    FSimplifyWithTactic,
    FClassifyDecision,
    FSolveShortcut,
    FMapStep,
    FMapEnsureError,
    FVisitAssumption,
    FTryGuardedSolve,
    FRegisterBlockedHint,
    FMapUnsupportedErr,
    FSolveRewrite,
>(
    state: &mut T,
    lhs: ExprId,
    base: ExprId,
    exponent: ExprId,
    rhs: ExprId,
    op: RelOp,
    var: &str,
    mode: crate::log_domain::DomainModeKind,
    wildcard_scope: bool,
    value_domain_real_only: bool,
    budget: crate::solve_budget::SolveBudget,
    collect_item: FCollectItem,
    build_tactic_options: FBuildTacticOptions,
    existing_steps: Vec<S>,
    context_ref: FContextRef,
    context_mut: FContextMut,
    render_expr: FRenderExpr,
    isolate_base: FIsolateBase,
    simplify_shortcut: FSimplifyShortcut,
    clear_blocked_hints: FClearBlockedHints,
    simplify_with_tactic: FSimplifyWithTactic,
    classify_decision: FClassifyDecision,
    solve_shortcut: FSolveShortcut,
    map_step: FMapStep,
    map_ensure_error: FMapEnsureError,
    visit_assumption: FVisitAssumption,
    try_guarded_solve: FTryGuardedSolve,
    register_blocked_hint: FRegisterBlockedHint,
    map_unsupported_err: FMapUnsupportedErr,
    solve_rewrite: FSolveRewrite,
) -> Result<(SolutionSet, Vec<S>), E>
where
    S: Clone,
    FCollectItem: FnMut(&mut T) -> bool,
    FBuildTacticOptions: FnOnce() -> TTacticOptions,
    FContextRef: Fn(&mut T) -> &cas_ast::Context,
    FContextMut: Fn(&mut T) -> &mut cas_ast::Context,
    FRenderExpr: Fn(&cas_ast::Context, ExprId) -> String,
    FIsolateBase: FnMut(&mut T, ExprId, ExprId, RelOp) -> Result<(SolutionSet, Vec<S>), E>,
    FSimplifyShortcut: FnMut(&mut T, ExprId) -> ExprId,
    FClearBlockedHints: FnMut(&mut T),
    FSimplifyWithTactic: FnMut(&mut T, ExprId, &TTacticOptions) -> ExprId,
    FClassifyDecision: FnMut(&mut T, ExprId, ExprId) -> crate::log_domain::LogSolveDecision,
    FSolveShortcut: FnMut(&mut T, ExprId, RelOp) -> Result<(SolutionSet, Vec<S>), E>,
    FMapStep: FnMut(String, Equation) -> S,
    FMapEnsureError: FnMut(&str, &'static str) -> E,
    FVisitAssumption: FnMut(&cas_ast::Context, crate::log_domain::LogAssumption),
    FTryGuardedSolve: FnMut(&mut T, &Equation) -> Option<SolutionSet>,
    FRegisterBlockedHint: FnMut(&cas_ast::Context, crate::solve_outcome::LogBlockedHintRecord),
    FMapUnsupportedErr: FnMut(&'static str) -> E,
    FSolveRewrite: FnMut(&mut T, &Equation) -> Result<(SolutionSet, Vec<S>), E>,
{
    let collect_item = std::cell::RefCell::new(collect_item);
    let config = build_pow_isolation_runtime_config_with_state(
        state,
        mode,
        wildcard_scope,
        value_domain_real_only,
        budget,
        |state| (collect_item.borrow_mut())(state),
        build_tactic_options,
    );

    execute_pow_isolation_with_runtime_config_and_unified_step_mapper_for_var_with_state(
        state,
        lhs,
        base,
        exponent,
        rhs,
        op,
        var,
        config,
        existing_steps,
        context_ref,
        context_mut,
        render_expr,
        isolate_base,
        simplify_shortcut,
        clear_blocked_hints,
        simplify_with_tactic,
        |state| (collect_item.borrow_mut())(state),
        classify_decision,
        solve_shortcut,
        map_step,
        map_ensure_error,
        visit_assumption,
        try_guarded_solve,
        register_blocked_hint,
        map_unsupported_err,
        solve_rewrite,
    )
}

/// Execute power isolation with default runtime config and a single recursive
/// equation solver callback reused across base/shortcut/rewrite/guarded paths.
#[allow(clippy::too_many_arguments)]
pub fn apply_pow_isolation_with_default_runtime_config_and_recursive_equation_solver_with_state<
    T,
    S,
    E,
    TTacticOptions,
    FCollectItem,
    FBuildTacticOptions,
    FContextRef,
    FContextMut,
    FRenderExpr,
    FSimplifyShortcut,
    FClearBlockedHints,
    FSimplifyWithTactic,
    FClassifyDecision,
    FSolveEquation,
    FMapStep,
    FMapEnsureError,
    FVisitAssumption,
    FRegisterBlockedHint,
    FMapUnsupportedErr,
>(
    state: &mut T,
    lhs: ExprId,
    base: ExprId,
    exponent: ExprId,
    rhs: ExprId,
    op: RelOp,
    var: &str,
    mode: crate::log_domain::DomainModeKind,
    wildcard_scope: bool,
    value_domain_real_only: bool,
    budget: crate::solve_budget::SolveBudget,
    collect_item: FCollectItem,
    build_tactic_options: FBuildTacticOptions,
    existing_steps: Vec<S>,
    context_ref: FContextRef,
    context_mut: FContextMut,
    render_expr: FRenderExpr,
    simplify_shortcut: FSimplifyShortcut,
    clear_blocked_hints: FClearBlockedHints,
    simplify_with_tactic: FSimplifyWithTactic,
    classify_decision: FClassifyDecision,
    solve_equation: FSolveEquation,
    map_step: FMapStep,
    map_ensure_error: FMapEnsureError,
    visit_assumption: FVisitAssumption,
    register_blocked_hint: FRegisterBlockedHint,
    map_unsupported_err: FMapUnsupportedErr,
) -> Result<(SolutionSet, Vec<S>), E>
where
    S: Clone,
    FCollectItem: FnMut(&mut T) -> bool,
    FBuildTacticOptions: FnOnce() -> TTacticOptions,
    FContextRef: Fn(&mut T) -> &cas_ast::Context,
    FContextMut: Fn(&mut T) -> &mut cas_ast::Context,
    FRenderExpr: Fn(&cas_ast::Context, ExprId) -> String,
    FSimplifyShortcut: FnMut(&mut T, ExprId) -> ExprId,
    FClearBlockedHints: FnMut(&mut T),
    FSimplifyWithTactic: FnMut(&mut T, ExprId, &TTacticOptions) -> ExprId,
    FClassifyDecision: FnMut(&mut T, ExprId, ExprId) -> crate::log_domain::LogSolveDecision,
    FSolveEquation: FnMut(&mut T, Equation, &str) -> Result<(SolutionSet, Vec<S>), E>,
    FMapStep: FnMut(String, Equation) -> S,
    FMapEnsureError: FnMut(&str, &'static str) -> E,
    FVisitAssumption: FnMut(&cas_ast::Context, crate::log_domain::LogAssumption),
    FRegisterBlockedHint: FnMut(&cas_ast::Context, crate::solve_outcome::LogBlockedHintRecord),
    FMapUnsupportedErr: FnMut(&'static str) -> E,
{
    let solve_equation = std::cell::RefCell::new(solve_equation);
    apply_pow_isolation_with_default_runtime_config_and_unified_step_mapper_for_var_with_state(
        state,
        lhs,
        base,
        exponent,
        rhs,
        op,
        var,
        mode,
        wildcard_scope,
        value_domain_real_only,
        budget,
        collect_item,
        build_tactic_options,
        existing_steps,
        context_ref,
        context_mut,
        render_expr,
        |state, iso_lhs, iso_rhs, iso_op| {
            (solve_equation.borrow_mut())(
                state,
                Equation {
                    lhs: iso_lhs,
                    rhs: iso_rhs,
                    op: iso_op,
                },
                var,
            )
        },
        simplify_shortcut,
        clear_blocked_hints,
        simplify_with_tactic,
        classify_decision,
        |state, shortcut_rhs, shortcut_op| {
            (solve_equation.borrow_mut())(
                state,
                Equation {
                    lhs: exponent,
                    rhs: shortcut_rhs,
                    op: shortcut_op,
                },
                var,
            )
        },
        map_step,
        map_ensure_error,
        visit_assumption,
        |state, equation| {
            (solve_equation.borrow_mut())(state, equation.clone(), var)
                .ok()
                .map(|(solutions, _)| solutions)
        },
        register_blocked_hint,
        map_unsupported_err,
        |state, equation| (solve_equation.borrow_mut())(state, equation.clone(), var),
    )
}
