//! Shared runtime adapter for isolation dispatch with standard mappers.

use cas_ast::symbol::SymbolId;
use cas_ast::{Equation, ExprId, RelOp, SolutionSet};

/// Dispatch isolation using shared default route/error/step mappers.
#[allow(clippy::too_many_arguments)]
pub fn dispatch_isolation_with_default_routes_and_mappers_with_state<
    T,
    TTacticOptions,
    FContextRef,
    FContextMut,
    FSimplifyRhs,
    FCollectLinearItem,
    FSimplifyLinearExpr,
    FProveNonzeroStatus,
    FRenderExpr,
    FCollectRouteItem,
    FSolveSplitCaseWithVar,
    FIsKnownNegative,
    FIsolateRewrittenWithVar,
    FCollectPowItem,
    FSimplifyShortcut,
    FClearBlockedHints,
    FSimplifyWithTactic,
    FClassifyDecision,
    FMapPowEnsureError,
    FVisitPowAssumption,
    FRegisterBlockedHint,
    FMapPowUnsupportedErr,
    FCollectFunctionItems,
    FSimplifyWithTrace,
    FSymName,
    FSolveEquationWithVar,
    FCollectNegatedItem,
>(
    state: &mut T,
    lhs: ExprId,
    rhs: ExprId,
    op: RelOp,
    var: &str,
    context_ref: FContextRef,
    context_mut: FContextMut,
    simplify_rhs: FSimplifyRhs,
    collect_linear_item: FCollectLinearItem,
    simplify_linear_expr: FSimplifyLinearExpr,
    prove_nonzero_status: FProveNonzeroStatus,
    render_expr: FRenderExpr,
    collect_route_item: FCollectRouteItem,
    solve_split_case_with_var: FSolveSplitCaseWithVar,
    is_known_negative: FIsKnownNegative,
    isolate_rewritten_with_var: FIsolateRewrittenWithVar,
    mode: crate::log_domain::DomainModeKind,
    wildcard_scope: bool,
    value_domain_real_only: bool,
    budget: crate::solve_budget::SolveBudget,
    collect_pow_item: FCollectPowItem,
    tactic_options: TTacticOptions,
    simplify_shortcut: FSimplifyShortcut,
    clear_blocked_hints: FClearBlockedHints,
    simplify_with_tactic: FSimplifyWithTactic,
    classify_decision: FClassifyDecision,
    map_pow_ensure_error: FMapPowEnsureError,
    visit_pow_assumption: FVisitPowAssumption,
    register_blocked_hint: FRegisterBlockedHint,
    map_pow_unsupported_err: FMapPowUnsupportedErr,
    collect_function_items: FCollectFunctionItems,
    simplify_with_trace: FSimplifyWithTrace,
    sym_name: FSymName,
    solve_equation_with_var: FSolveEquationWithVar,
    collect_negated_item: FCollectNegatedItem,
) -> Result<
    (
        SolutionSet,
        Vec<crate::solve_runtime_mapping::DefaultSolveStep>,
    ),
    crate::error_model::CasError,
>
where
    TTacticOptions: Clone,
    FContextRef: Fn(&mut T) -> &cas_ast::Context,
    FContextMut: Fn(&mut T) -> &mut cas_ast::Context,
    FSimplifyRhs: FnMut(&mut T, ExprId) -> ExprId,
    FCollectLinearItem: FnMut(&mut T) -> bool,
    FSimplifyLinearExpr: FnMut(&mut T, ExprId) -> ExprId,
    FProveNonzeroStatus: FnMut(&mut T, ExprId) -> crate::linear_solution::NonZeroStatus,
    FRenderExpr: Fn(&cas_ast::Context, ExprId) -> String,
    FCollectRouteItem: FnMut(&mut T) -> bool,
    FSolveSplitCaseWithVar: FnMut(
        &mut T,
        &Equation,
        &str,
    ) -> Result<
        (
            SolutionSet,
            Vec<crate::solve_runtime_mapping::DefaultSolveStep>,
        ),
        crate::error_model::CasError,
    >,
    FIsKnownNegative: FnMut(&mut T, ExprId) -> bool,
    FIsolateRewrittenWithVar: FnMut(
        &mut T,
        Equation,
        &str,
    ) -> Result<
        (
            SolutionSet,
            Vec<crate::solve_runtime_mapping::DefaultSolveStep>,
        ),
        crate::error_model::CasError,
    >,
    FCollectPowItem: FnMut(&mut T) -> bool,
    FSimplifyShortcut: FnMut(&mut T, ExprId) -> ExprId,
    FClearBlockedHints: FnMut(&mut T),
    FSimplifyWithTactic: FnMut(&mut T, ExprId, &TTacticOptions) -> ExprId,
    FClassifyDecision: FnMut(&mut T, ExprId, ExprId) -> crate::log_domain::LogSolveDecision,
    FMapPowEnsureError: FnMut(&str, &'static str) -> crate::error_model::CasError,
    FVisitPowAssumption: FnMut(&cas_ast::Context, ExprId, ExprId, crate::log_domain::LogAssumption),
    FRegisterBlockedHint: FnMut(&cas_ast::Context, crate::solve_outcome::LogBlockedHintRecord),
    FMapPowUnsupportedErr: FnMut(&'static str) -> crate::error_model::CasError,
    FCollectFunctionItems: FnMut(&mut T) -> bool,
    FSimplifyWithTrace: FnMut(&mut T, ExprId) -> (ExprId, Vec<(String, ExprId)>),
    FSymName: FnMut(&mut T, SymbolId) -> String,
    FSolveEquationWithVar: FnMut(
        &mut T,
        Equation,
        &str,
    ) -> Result<
        (
            SolutionSet,
            Vec<crate::solve_runtime_mapping::DefaultSolveStep>,
        ),
        crate::error_model::CasError,
    >,
    FCollectNegatedItem: FnMut(&mut T) -> bool,
{
    crate::solve_runtime_flow::dispatch_isolation_with_default_kernels_and_default_arithmetic_pow_function_routes_with_state(
        state,
        lhs,
        rhs,
        op,
        var,
        context_ref,
        context_mut,
        simplify_rhs,
        collect_linear_item,
        simplify_linear_expr,
        prove_nonzero_status,
        render_expr,
        collect_route_item,
        solve_split_case_with_var,
        is_known_negative,
        isolate_rewritten_with_var,
        mode,
        wildcard_scope,
        value_domain_real_only,
        budget,
        collect_pow_item,
        tactic_options,
        simplify_shortcut,
        clear_blocked_hints,
        simplify_with_tactic,
        classify_decision,
        map_pow_ensure_error,
        visit_pow_assumption,
        register_blocked_hint,
        map_pow_unsupported_err,
        collect_function_items,
        simplify_with_trace,
        sym_name,
        |_state, missing_var| {
            crate::solve_runtime_mapping::map_variable_not_found_solver_error(missing_var)
        },
        |_state, unsupported_var, message| {
            crate::solve_runtime_mapping::map_isolation_error(unsupported_var, message)
        },
        |_state, fn_name| crate::solve_runtime_mapping::map_unknown_function_error(fn_name),
        solve_equation_with_var,
        collect_negated_item,
        crate::solve_runtime_mapping::medium_step,
        |_state, lhs_expr| {
            crate::solve_runtime_mapping::map_isolation_cannot_isolate_error(var, lhs_expr)
        },
    )
}
