#!/usr/bin/env python3
"""Maintenance tool for docs/ENGINE_COMBINATION_LEDGER.md.

The combination ledger is the working memory of the engine auto-improvement
loop. It grows by several entries per working day and is consulted by agents
with bounded context, so it needs two maintenance operations that this tool
owns:

- ``--reindex``: regenerate the entry index between the ``BEGIN ENTRY INDEX``
  and ``END ENTRY INDEX`` markers in the active ledger header, one line per
  entry (date | status | area | title), newest first, plus a list of archive
  files.
- ``--rotate YYYY-MM``: move every entry dated in that month into
  ``ENGINE_COMBINATION_LEDGER_ARCHIVE_YYYY_MM.md`` next to the active ledger,
  preserving entry bodies byte-for-byte and their relative order. The current
  month cannot be rotated.

Entry headings have the shape ``## YYYY-MM-DD - title``. Everything before the
first such heading is the ledger header and is never rotated. The scorecard's
``generated_discovery_ledger_metrics`` reads the active ledger plus all
archive files, so rotation never changes scorecard metrics.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DEFAULT_LEDGER = ROOT / "docs" / "ENGINE_COMBINATION_LEDGER.md"

ENTRY_HEADING = re.compile(r"^## (?P<date>\d{4}-\d{2}-\d{2}) - (?P<title>.+)$", re.M)
INDEX_BEGIN = "<!-- BEGIN ENTRY INDEX (generated by scripts/engine_combination_ledger_tool.py --reindex; do not edit by hand) -->"
INDEX_END = "<!-- END ENTRY INDEX -->"


def split_ledger(text: str) -> tuple[str, list[dict[str, str]]]:
    """Split ledger text into (header, entries). Entry bodies keep their heading."""
    matches = list(ENTRY_HEADING.finditer(text))
    if not matches:
        return text, []
    header = text[: matches[0].start()]
    entries = []
    for index, match in enumerate(matches):
        end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
        entries.append(
            {
                "date": match.group("date"),
                "title": match.group("title").strip(),
                "body": text[match.start() : end],
            }
        )
    return header, entries


def field_block(body: str, field: str) -> str:
    """Return the condensed first line of a `- field:` block, or ''."""
    match = re.search(
        rf"^- {re.escape(field)}:\s*\n\s+-?\s*(?P<value>.+)$", body, re.M
    )
    if not match:
        match = re.search(rf"^- {re.escape(field)}:\s*(?P<value>\S.*)$", body, re.M)
    if not match:
        return ""
    return " ".join(match.group("value").split())


def entry_status(body: str) -> str:
    raw = field_block(body, "status")
    ticked = re.search(r"`([^`]+)`", raw)
    return ticked.group(1) if ticked else (raw or "unknown")


def entry_area(body: str) -> str:
    return field_block(body, "area") or "unknown"


def archive_path(ledger: pathlib.Path, month: str) -> pathlib.Path:
    return ledger.parent / f"{ledger.stem}_ARCHIVE_{month.replace('-', '_')}.md"


def archive_files(ledger: pathlib.Path) -> list[pathlib.Path]:
    return sorted(ledger.parent.glob(f"{ledger.stem}_ARCHIVE_*.md"))


def build_index(ledger: pathlib.Path, entries: list[dict[str, str]]) -> str:
    lines = [INDEX_BEGIN]
    archives = archive_files(ledger)
    if archives:
        lines.append("")
        lines.append("Archived months (rotated, still read by scorecard metrics):")
        for path in archives:
            lines.append(f"- [{path.name}]({path.name})")
    lines.append("")
    lines.append(f"Active entries: {len(entries)} (newest first)")
    lines.append("")
    for entry in sorted(entries, key=lambda e: e["date"], reverse=True):
        status = entry_status(entry["body"])
        area = entry_area(entry["body"])
        if len(area) > 80:
            area = area[:77] + "..."
        lines.append(f"- {entry['date']} | `{status}` | {area} | {entry['title']}")
    lines.append(INDEX_END)
    return "\n".join(lines)


def replace_index(header: str, index_block: str) -> str:
    begin = header.find(INDEX_BEGIN)
    end = header.find(INDEX_END)
    if begin != -1 and end != -1:
        return header[:begin] + index_block + header[end + len(INDEX_END) :]
    # First run: insert the index just before the end of the header.
    return header.rstrip("\n") + "\n\n" + index_block + "\n\n"


def reindex(ledger: pathlib.Path) -> int:
    text = ledger.read_text()
    header, entries = split_ledger(text)
    new_header = replace_index(header, build_index(ledger, entries))
    ledger.write_text(new_header + "".join(entry["body"] for entry in entries))
    print(f"reindexed: {len(entries)} active entries, {len(archive_files(ledger))} archives")
    return 0


def rotate(ledger: pathlib.Path, months: list[str], today: _dt.date) -> int:
    current_month = today.strftime("%Y-%m")
    for month in months:
        if not re.fullmatch(r"\d{4}-\d{2}", month):
            print(f"error: month must be YYYY-MM, got {month}", file=sys.stderr)
            return 2
        if month >= current_month:
            print(f"error: refusing to rotate current/future month {month}", file=sys.stderr)
            return 2

    text = ledger.read_text()
    header, entries = split_ledger(text)
    total_before = len(entries)

    # Plan every move in memory and verify integrity before writing anything.
    moves: dict[str, list[dict[str, str]]] = {}
    kept = entries
    for month in months:
        moves[month] = [e for e in kept if e["date"].startswith(month)]
        kept = [e for e in kept if not e["date"].startswith(month)]
    moved_total = sum(len(moved) for moved in moves.values())
    if moved_total + len(kept) != total_before:
        print("error: integrity check failed, aborting without writes", file=sys.stderr)
        return 1

    for month, moved in moves.items():
        if not moved:
            print(f"{month}: no entries to rotate")
            continue
        target = archive_path(ledger, month)
        if target.exists():
            archive_text = target.read_text()
        else:
            archive_text = (
                f"# Engine Combination Ledger - Archive {month}\n\n"
                f"Entries rotated from [ENGINE_COMBINATION_LEDGER.md](ENGINE_COMBINATION_LEDGER.md).\n"
                f"Scorecard discovery metrics still read this file; treat it as\n"
                f"read-only history and do not add new entries here.\n\n"
            )
        target.write_text(archive_text + "".join(e["body"] for e in moved))
        print(f"{month}: rotated {len(moved)} entries -> {target.name}")

    ledger.write_text(header + "".join(entry["body"] for entry in kept))
    print(f"active entries: {total_before} -> {len(kept)}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ledger", type=pathlib.Path, default=DEFAULT_LEDGER)
    parser.add_argument("--rotate", nargs="+", metavar="YYYY-MM", default=None)
    parser.add_argument("--reindex", action="store_true")
    args = parser.parse_args()

    if not args.rotate and not args.reindex:
        print("nothing to do: pass --rotate and/or --reindex", file=sys.stderr)
        return 2
    if args.rotate:
        code = rotate(args.ledger, args.rotate, _dt.date.today())
        if code != 0:
            return code
    if args.reindex:
        return reindex(args.ledger)
    return 0


if __name__ == "__main__":
    sys.exit(main())
