#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ReplCommandInput<'a> {
    Help(&'a str),
    Let(&'a str),
    Assignment {
        name: &'a str,
        expr: &'a str,
        lazy: bool,
    },
    Vars,
    Clear(&'a str),
    Reset,
    ResetFull,
    Cache(&'a str),
    Semantics(&'a str),
    Context(&'a str),
    Steps(&'a str),
    Autoexpand(&'a str),
    Budget(&'a str),
    History,
    Show(&'a str),
    Del(&'a str),
    Set(&'a str),
    Equiv(&'a str),
    Subst(&'a str),
    SolveSystem(&'a str),
    Solve(&'a str),
    Simplify(&'a str),
    Config(&'a str),
    Timeline(&'a str),
    Visualize(&'a str),
    Explain(&'a str),
    Det(&'a str),
    Transpose(&'a str),
    Trace(&'a str),
    Telescope(&'a str),
    Weierstrass(&'a str),
    ExpandLog(&'a str),
    Expand(&'a str),
    Rationalize(&'a str),
    Limit(&'a str),
    Profile(&'a str),
    Health(&'a str),
    Eval(&'a str),
}
