mod css;
mod script;

use self::css::SOLVE_TIMELINE_EXTRA_CSS;
use self::script::SOLVE_TIMELINE_SUBSTEPS_SCRIPT;
use super::page_shell::{
    render_timeline_page_footer, render_timeline_page_header, TimelinePageShell,
};
use cas_formatter::html_escape;

pub(super) fn render_solve_timeline_html_header(
    title: &str,
    var: &str,
    original_latex: &str,
) -> String {
    let subtitle_html = format!("Solving for <strong>{}</strong>", html_escape(var));
    render_timeline_page_header(TimelinePageShell {
        page_title_prefix: "Solve Steps",
        title,
        heading: "Equation Solving Steps",
        subtitle_html: &subtitle_html,
        original_label: "Original Equation:",
        original_latex,
        extra_css: SOLVE_TIMELINE_EXTRA_CSS,
    })
}

pub(super) fn solve_timeline_html_footer() -> String {
    render_timeline_page_footer(
        "Generated by Rust CAS Engine - Equation Solver",
        Some(SOLVE_TIMELINE_SUBSTEPS_SCRIPT),
    )
}
