use super::page_shell::{
    render_timeline_page_footer, render_timeline_page_header, TimelinePageShell,
};
use cas_formatter::html_escape;

const SOLVE_TIMELINE_EXTRA_CSS: &str = r#"
    :root {
        --footer-color: white;
    }
    .description {
        color: var(--description-color);
        font-size: 1em;
        margin-bottom: 10px;
        font-style: italic;
        transition: color 0.3s ease;
    }
    .equation {
        background: var(--equation-bg);
        padding: 15px;
        border-radius: 8px;
        text-align: center;
        font-size: 1.2em;
        transition: background 0.3s ease;
        overflow-x: auto;
        max-width: 100%;
    }
    .substeps-toggle {
        display: flex;
        align-items: center;
        gap: 8px;
        margin-top: 12px;
        padding: 8px 12px;
        background: rgba(100, 181, 246, 0.15);
        border-radius: 6px;
        cursor: pointer;
        font-size: 0.9em;
        color: var(--step-number-color);
        border: 1px solid rgba(100, 181, 246, 0.3);
        transition: all 0.2s ease;
    }
    .substeps-toggle:hover {
        background: rgba(100, 181, 246, 0.25);
    }
    .substeps-toggle .arrow {
        transition: transform 0.3s ease;
        font-size: 0.8em;
    }
    .substeps-toggle.expanded .arrow {
        transform: rotate(90deg);
    }
    .substeps-container {
        display: none;
        margin-top: 12px;
        padding-left: 20px;
        border-left: 2px solid rgba(100, 181, 246, 0.3);
    }
    .substeps-container.visible {
        display: block;
        animation: slideDown 0.3s ease;
    }
    @keyframes slideDown {
        from { opacity: 0; transform: translateY(-10px); }
        to { opacity: 1; transform: translateY(0); }
    }
    .substep {
        background: rgba(30, 40, 55, 0.6);
        border-radius: 8px;
        padding: 12px 15px;
        margin-bottom: 10px;
        border-left: 3px solid #90caf9;
    }
    .substep-number {
        color: #90caf9;
        font-weight: bold;
        font-size: 0.85em;
        margin-bottom: 4px;
    }
    .substep-description {
        color: var(--description-color);
        font-size: 0.9em;
        margin-bottom: 8px;
        font-style: italic;
    }
    .substep-equation {
        background: rgba(20, 30, 45, 0.8);
        padding: 10px;
        border-radius: 6px;
        text-align: center;
        font-size: 1em;
    }
"#;

const SOLVE_TIMELINE_SUBSTEPS_SCRIPT: &str = r#"    <script>
        function toggleSubsteps(id) {
            const container = document.getElementById(id);
            const toggle = document.querySelector(`[onclick*="${id}"]`);
            if (container.classList.contains('visible')) {
                container.classList.remove('visible');
                toggle.classList.remove('expanded');
                toggle.querySelector('span:last-child').textContent = 'Show derivation (' + container.children.length + ' steps)';
            } else {
                container.classList.add('visible');
                toggle.classList.add('expanded');
                toggle.querySelector('span:last-child').textContent = 'Hide derivation';
                if (window.MathJax) {
                    MathJax.typeset([container]);
                }
            }
        }
    </script>
"#;

pub(super) fn render_solve_timeline_html_header(
    title: &str,
    var: &str,
    original_latex: &str,
) -> String {
    let subtitle_html = format!("Solving for <strong>{}</strong>", html_escape(var));
    render_timeline_page_header(TimelinePageShell {
        page_title_prefix: "Solve Steps",
        title,
        heading: "Equation Solving Steps",
        subtitle_html: &subtitle_html,
        original_label: "Original Equation:",
        original_latex,
        extra_css: SOLVE_TIMELINE_EXTRA_CSS,
    })
}

pub(super) fn solve_timeline_html_footer() -> String {
    render_timeline_page_footer(
        "Generated by Rust CAS Engine - Equation Solver",
        Some(SOLVE_TIMELINE_SUBSTEPS_SCRIPT),
    )
}
